Add demo data-warehouse-iceberg-trino-spark
stackabletech/stackablectl pull request #144
Opened 2022-10-14 11:19 UTC by sbernauer

## Description

Needs a larger k8s cluster! I use IONOS k8s with 9x 4 cores (8 threads), 20GB ram and 30GB hdd disk
Maybe we can also offer a smaller variant later on.

Otherwise business as usual. From feature-branch run `stackablectl --additional-stacks-file stacks/stacks-v1.yaml --additional-releases-file releases.yaml --additional-demos-file demos/demos-v1.yaml demo install data-warehouse-iceberg-trino-spark`

I'm not happy with some parts but i think an iterative approach is best:
* Shared bikes are currently not streamed into Kafka (instead on-time job)
* Some high-volume real-time datasource would be great. Currently we use the water levels and duplicate them to get higher volumes.
* Some sort of Upsert or Deletion usecases would be great. But probably not on the large datasets as for our wallet ^^
* Better Dashboards. The current one were thrown together in like 30 mins. We can e.g. doe the same graphs as in the water-level, earthquakes and taxi-data demo
* I would like to partitions the water_level measurements by day but run into https://github.com/apache/iceberg/issues/5625. There might be ways around by using a dedicated Spark context for compaction but we can easily adopt the partitioning after the issue gets fixed. Sorting during rewrites did cost performance during compaction and did not provide real benefits for my intial measurements. Disabled for now.
* As always tracked my findings in https://github.com/stackabletech/stackablectl/issues/128

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-10-14 16:21 UTC, maltesander approved these changes
Nice. LGTM!

2022-10-17 06:50 UTC, sbernauer commented
I kept running over the weekend. We now are a
```
|files|total_size     |avg_size   |total_records |avg_records|smallest_file|
|-----|---------------|-----------|--------------|-----------|-------------|
|298  |150,318,197,593|504,423,481|36,430,087,583|122,248,616|7,101,325    |
```

2022-11-02 13:31 UTC, sbernauer commented
@maltesander could you please do another round reviewing the docs?

2022-11-02 16:29 UTC, maltesander requested changes
Just english nitpicking!

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +It was developed and tested on 10 nodes with 4 cores (8 threads), 20GB RAM and 30GB hdd disks.
```suggestion
It was developed and tested on 10 nodes with each 4 cores (8 threads), 20GB RAM and 30GB HDD.
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +Additionally persistent volumes with a total size of approx. 1TB will get created.
```suggestion
Additionally, persistent volumes with a total size of approximately 1TB will get created.
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +This guide assumes you already have the demo `data-warehouse-iceberg-trino-spark` installed.
```suggestion
This guide assumes that you already have the demo `data-warehouse-iceberg-trino-spark` installed.
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +** *NiFi*:  An easy-to-use, powerful system to process and distribute data. This demos uses it to fetch multiple online real-time datasources and ingest it into Kafka
```suggestion
** *Kafka*: A distributed event streaming platform for high-performance data pipelines, streaming analytics and data integration. This demos uses it as an event streaming platform to stream the data in near real-time
** *NiFi*: An easy-to-use, powerful system to process and distribute data. This demos uses it to fetch multiple online real-time data sources and ingest it into Kafka
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +** *Open policy agent* (OPA): A open source, general-purpose policy engine that unifies policy enforcement across the stack. This demo uses it as the authorizer for Trino, which decides which user is
```suggestion
** *Open policy agent* (OPA): An open source, general-purpose policy engine that unifies policy enforcement across the stack. This demo uses it as the authorizer for Trino, which decides which user is able to query which data.
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +* Copy multiple datasources in csv and parquet format into the s3 staging area
```suggestion
* Copy multiple data sources in CSV and Parquet format into the S3 staging area
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +* Simultaneously start a NiFi workflow, which fetches real-time datasets via the internet and ingests the data as json records into Kafka
```suggestion
* Simultaneously start a NiFi workflow, which fetches datasets in real-time via the internet and ingests the data as JSON records into Kafka
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +This demos uses Iceberg as it plays along nicely with Object storages as well as having a Trino and Spark integration.
```suggestion
This demos uses Iceberg as it plays along nicely with object storage as well as having a Trino and Spark integration.
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +Here you can see the two buckets the S3 is split into:
```suggestion
Here you can see the two buckets contained in the S3:
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +1. `staging`: The demo loads static datasets into this area. It is stored in different formats, such as csv and parquet. It does contain actual data tables as well as lookup tables.
```suggestion
1. `staging`: The demo loads static datasets into this area. It is stored in different formats, such as CSV and Parquet. It does contain actual data tables as well as lookup tables.
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +Some of the datasources are statically download (e.g. as csv) and others are fetch via APIs such as REST APIs.
```suggestion
Some data sources are statically downloaded (e.g. as CSV) and others are dynamically fetched via APIs such as REST APIs.
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +This includes the following datasources:
```suggestion
This includes the following data sources:
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +As you can see, the NiFi workflow consists of lot's of components.
```suggestion
As you can see, the NiFi workflow consists of lots of components.
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +Starting all of the product instances might take a considerable amount of time depending on your internet connectivity.
```suggestion
Starting all the product instances might take a considerable amount of time depending on your internet connectivity.
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +1. Fetch the list of known water-level stations and ingests them into Kafka
```suggestion
1. Fetch the list of known water-level stations and ingest them into Kafka
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +2. Continuously run a loop fetching the measurements of the last 30 for every measuring stations and ingesting the measurements into Kafka
```suggestion
2. Continuously run a loop fetching the measurements of the last 30 for every measuring station and ingesting the measurements into Kafka
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +3. Fetch the current shred bike bike status
bike bike status :) ?
```suggestion
1. Fetch the current shared bike stations information
2. Fetch the current shared bike stations status
3. Fetch the current shared bike bike status
```

2022-11-02 16:29 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +Additionally no need to add the setting `SSLVerification` and set it to `NONE`.
```suggestion
Additionally, set `SSLVerification` to `NONE`.
```

2022-11-03 12:54 UTC, sbernauer commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +Additionally no need to add the setting `SSLVerification` and set it to `NONE`.
This actually is a 2-step process. First adding, later setting the value

2022-11-03 13:04 UTC, sbernauer commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +Please have a look at the <TODO> trino-operator documentation on how to connect DBeaver to Trino.
Extracted into https://github.com/stackabletech/trino-operator/issues/321

2022-11-03 13:53 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +Please have a look at the <TODO> trino-operator documentation on how to connect DBeaver to Trino.
We should create a ticket for that once its done to adapt it here?

2022-11-03 13:58 UTC, sbernauer commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +Please have a look at the <TODO> trino-operator documentation on how to connect DBeaver to Trino.
Its in the definition of done in that ticket ;)

2022-11-03 13:58 UTC, sbernauer commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +Additionally no need to add the setting `SSLVerification` and set it to `NONE`.
Arghhhh, nevermind. Setting it to

Additionally, you need to add the setting `SSLVerification` and set it to `NONE`

2022-11-03 14:02 UTC, maltesander commented on docs/modules/ROOT/pages/demos/data-warehouse-iceberg-trino-spark.adoc
> +Please have a look at the <TODO> trino-operator documentation on how to connect DBeaver to Trino.
OK

2022-11-03 14:02 UTC, maltesander approved these changes
LGTM!

2022-11-03 14:50 UTC, sbernauer commented
Many many thanks!

2022-11-03 14:50 UTC, sbernauer commented
bors r+

2022-11-03 14:52 UTC, closed without merging