Logging
stackabletech/stackablectl pull request #187
Opened 2022-12-08 12:46 UTC by siegfriedweber

## Description

- Show opensearch-dashboards service with `stackablectl services list`.
- Add logging demo.

TODOs before merging:
- [ ] `demos/demos-v1.yaml`: Replace `https://raw.githubusercontent.com/stackabletech/stackablectl/logging/demos/logging/zookeeper.yaml` with `https://raw.githubusercontent.com/stackabletech/stackablectl/main/demos/logging/zookeeper.yaml`.
- [ ] `demos/logging/zookeeper.yaml`: Remove `repo: docker.stackable.tech/sandbox/logging` when stackabletech/docker-images#268 is merged and the images are built and deployed.
- [ ] `releases/releases.yaml`: Remove the file when the logging branch of the zookeeper-operator is merged.
- [ ] `stacks/stacks-v1.yaml`: Replace `stackableRelease: 22.11-logging` with `stackableRelease: 22.11`.
- [ ] `stacks/stacks-v1.yaml`: Replace `https://raw.githubusercontent.com/stackabletech/stackablectl/logging/stacks/logging/vector-aggregator-discovery.yaml` with `
https://raw.githubusercontent.com/stackabletech/stackablectl/main/stacks/logging/vector-aggregator-discovery.yaml`.

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-12-12 13:39 UTC, fhennig requested changes
I've only read this docs page for now, and I have this one comment.

i've ran the demo on my machine and it worked!

2022-12-12 13:53 UTC, sbernauer commented on docs/modules/ROOT/nav.adoc
> +** xref:demos/logging.adoc[]
Not sure where to put this docs. Fine for me for now, as long as we have not decided how to ship the whole logging stack.

2022-12-12 13:53 UTC, sbernauer commented on src/services.rs
> +            (
We can get rid of this as we just list services, can't we?

2022-12-12 13:53 UTC, sbernauer commented on stacks/stacks-v1.yaml
> +        extraObjects:
We can also throw in the CM `vector-aggregator-discovery` here. Would make this thing more self-contained

2022-12-12 13:53 UTC, sbernauer commented
Demo worked for me as well

2022-12-12 14:35 UTC, sbernauer commented
![image](https://user-images.githubusercontent.com/29303194/207071905-17228a27-6013-422c-9a42-744882628b32.png)
my usual problems with elastic/Opensource (ordering of lines) :upside_down_face: But nothing we can do here afaik

2022-12-12 16:12 UTC, siegfriedweber commented on docs/modules/ROOT/nav.adoc
> +** xref:demos/logging.adoc[]
This is not the documentation for the stack. It is the documentation for the demo, so it should be listed together with the other demo documentations, shouldn't it?

2022-12-12 16:31 UTC, siegfriedweber commented on src/services.rs
> +            (
Yes, we can. This was a leftover of a prior implementation.

2022-12-13 07:37 UTC, sbernauer commented on stacks/stacks-v1.yaml
> +        extraObjects:
Agreed, missed that where are at the opensearch chart here

2022-12-13 07:38 UTC, sbernauer commented on docs/modules/ROOT/nav.adoc
> +** xref:demos/logging.adoc[]
Yes :)

2022-12-13 07:38 UTC, sbernauer approved these changes
Please wait for Felix

2022-12-13 12:25 UTC, fhennig commented on docs/modules/ROOT/pages/demos/logging.adoc
> +To check the current value, run this command:
```suggestion
== OpenSearch prerequisites

=== Mac and Windows
 If you're running on Mac or Windows and use Docker to run
Kubernetes, in menu:Preferences[Resources] set the RAM to at least 4GB.

=== Linux

OpenSearch uses a mmapfs directory by default to store its indices. The default
operating system limits on mmap counts is likely to be too low – usually 65530,
which may result in out of memory exceptions. So the Linux setting
`vm.max_map_count` on the host machine where kind is running, must be set to at
least 262144.

To check the current value, run this command:
```

2022-12-13 12:25 UTC, fhennig commented on docs/modules/ROOT/pages/demos/logging.adoc
> +To check the current value, run this command:
I'd do it like this

2022-12-15 16:07 UTC, siegfriedweber commented on docs/modules/ROOT/pages/demos/logging.adoc
> +To check the current value, run this command:
adopted

2022-12-19 11:14 UTC, fhennig approved these changes
I'm happy now :smiley: LGTM!

2022-12-19 14:29 UTC, sbernauer approved these changes
Happy as well

2022-12-19 14:30 UTC, siegfriedweber commented
bors merge

2022-12-19 14:31 UTC, closed without merging