Parameterize stacks and migrate logging and monitoring stack
stackabletech/stackablectl pull request #228
Opened 2023-02-13 07:38 UTC by sbernauer

## Description

*Please add a description here. This will become the commit message of the merge request later.*

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2023-02-13 13:19 UTC, maltesander requested changes
LGTM overall, just some nit picking. Did not test yet.

2023-02-13 13:19 UTC, maltesander commented on src/stack.rs
> +        parameters: Vec<String>,
```suggestion
        /// List of parameters to use when installing the stack.
        /// All parameters need to have the format `<parameter>=<value>`, e.g. `adminPassword=secret123`.
        /// Multiple parameters can be specified.
        /// Use `stackable stack describe <stack>` to list the available parameters.
        #[arg(short, long)]
        parameters: Vec<String>,
```

2023-02-13 13:19 UTC, maltesander commented on src/stack.rs
> +            let value = split.next().ok_or("Can not parse parameter. Parameters need to have the format `<parameter>=<value>`, e.g. `adminPassword=secret123`.")?;
Could be a const?

2023-02-13 13:19 UTC, maltesander commented on src/templating.rs
> +}
Optional: Could use a crate.

2023-02-13 13:23 UTC, sbernauer commented on src/demo.rs
> +        parameters: Vec<String>,
Was my first though as well.
My second was that "stack install -p foo=bar" and "demo install -p foo=bar" should look the same, hence calling the parameters only --parameters. The only exception is the parameters of the stack when installing the demo, where the name --parameters clashes

2023-02-13 14:33 UTC, maltesander reviewed
Logging Demo and Monitoring Stack work fine! Setting parameters works.
Changelog is missing.
LGTM otherwise.

2023-02-13 14:51 UTC, sbernauer commented on src/demo.rs
> +        "demos/demos-v2.yaml"
```suggestion
        "https://raw.githubusercontent.com/stackabletech/stackablectl/main/demos/demos-v2.yaml"
```

2023-02-13 14:51 UTC, sbernauer commented on src/stack.rs
> +        "stacks/stacks-v2.yaml"
```suggestion
       "https://raw.githubusercontent.com/stackabletech/stackablectl/main/stacks/stacks-v2.yaml"
```

2023-02-13 14:55 UTC, sbernauer commented on src/stack.rs
> +            let value = split.next().ok_or("Can not parse parameter. Parameters need to have the format `<parameter>=<value>`, e.g. `adminPassword=secret123`.")?;
cdd1a40aea9cc32e93b58aec11cb16eb2518f382

2023-02-13 15:20 UTC, sbernauer commented on src/templating.rs
> +}
aec4888c8bac0bf28b4dbe34516b3ac0dacb025d

2023-02-13 15:57 UTC, maltesander approved these changes
LGTM.

2023-02-14 11:50 UTC, sbernauer commented
bors r+

2023-02-14 11:51 UTC, closed without merging