OpenID & OPA PoC Demo
stackabletech/stackablectl pull request #283
Opened 2023-09-26 12:18 UTC by fhennig

## Description

*Please add a description here. This will become the commit message of the merge request later.*

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

2023-09-26 13:54 UTC, fhennig commented
Hey @sbernauer what needs to be done to merge this?

I think I'd like to rename the demo to `keycloak-opa-poc` what do you think?

2023-09-26 14:04 UTC, sbernauer commented
Question regarding merging is on Arch meeting agenda.
Name would work for me!

2023-09-26 14:05 UTC, sbernauer commented
It would be great if we could stick a section into the description that we have not decided yet if we want to go with userIds or userNames in the OPA rules

2023-09-27 12:51 UTC, sbernauer requested changes

2023-09-27 12:51 UTC, sbernauer commented on stacks/keycloak-opa-poc/druid.yaml
> +    tls: null
```suggestion
```

2023-09-27 12:51 UTC, sbernauer commented on stacks/keycloak-opa-poc/druid.yaml
> +      connString: jdbc:derby://localhost:1527/var/druid/metadata.db;create=true
postgres, e.g. https://github.com/stackabletech/stackablectl/blob/main/stacks/nifi-kafka-druid-superset-s3/druid.yaml and `https://raw.githubusercontent.com/stackabletech/stackablectl/main/stacks/_templates/postgresql-druid.yaml`

2023-09-27 12:51 UTC, sbernauer commented on stacks/keycloak-opa-poc/druid.yaml
> +        druid.auth.authenticator.MyBasicMetadataAuthenticator.initialInternalClientPassword: password2
Please check if needed (and in case yes, check if `initialAdminPassword` is needed) (and in case yes, please template via variable and default to e.g. `internalClientPassword`)
It would be awesome to read it from a Secret instead of putting plain credentials here

2023-09-27 12:51 UTC, sbernauer commented on stacks/keycloak-opa-poc/keycloak.yaml
> +# TODO: Fix "2023-09-18 14:43:46,327 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production."
TODO marker

2023-09-27 12:51 UTC, sbernauer commented on stacks/keycloak-opa-poc/opa.yaml
> +            kubernetes.io/os: linux
```suggestion
      default: {}
```

2023-09-27 12:51 UTC, sbernauer commented on stacks/keycloak-opa-poc/setup-keycloak.yaml
> +            ./kcadm.sh set-password --config kcadm.conf --username druid_system --new-password "password2"
Can this be removed? Or the second Authorizer in Druid?

2023-09-27 12:51 UTC, sbernauer commented on stacks/keycloak-opa-poc/zookeeper.yaml
> +    productVersion: 3.8.0
```suggestion
    productVersion: 3.8.1
```

2023-09-27 12:51 UTC, sbernauer commented on stacks/stacks-v2.yaml
> +    resourceRequests:
Please re-check once postgres is added

2023-09-27 14:38 UTC, fhennig commented on stacks/keycloak-opa-poc/druid.yaml
> +        druid.auth.authenticator.MyBasicMetadataAuthenticator.initialInternalClientPassword: password2
internal client password is in a secret; initialAdminPassword was removed -> no admin user created

2023-09-27 14:49 UTC, fhennig commented
@sbernauer thanks for the review, everything should be resolved. I suggest you also run the stack locally once to test it.

2023-09-29 08:11 UTC, fhennig commented on stacks/stacks-v2.yaml
> +      - helmChart: https://raw.githubusercontent.com/stackabletech/stackablectl/main/stacks/_templates/postgresql-druid.yaml
I've reordered all of them in the order they depend on each other, thanks!

2023-09-29 08:40 UTC, sbernauer approved these changes
LGTM % comments

2023-09-29 08:40 UTC, sbernauer commented on stacks/keycloak-opa-poc/policies.yaml
> +# A CM like this is created by the setup keycloak Job:
```suggestion
# A CM like this is created by the setup keycloak Job
# It is used for Druid roles, as we currently need to write them based on the user uuids.
```

2023-09-29 08:40 UTC, sbernauer commented on stacks/keycloak-opa-poc/policies.yaml
> +    import data.bundles.opagroups.admins
```suggestion
```

2023-09-29 08:40 UTC, sbernauer approved these changes

2023-09-29 08:46 UTC, merged