feat(stackabletctl): Support OCI registries
stackabletech/stackablectl pull request #344
Opened 2024-12-17 16:10 UTC by adwk67

# Description

This PR covers the following:

- addition of the option `--chart-source` that enables charts to be pulled either from an OCI registry (the default) or a Nexus repository
- retrieves tags from Harbor or Nexus for operator `list` and `describe` commands

>[!CAUTION]
>Do not merge & release before Jan 2025 as this will affect the kuttl tests.

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [x] Helm chart can be installed and deployed operator works
- [x] Tested commands with both options
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

2025-01-23 08:40 UTC, Techassi requested changes
Thank you for that feature! I left a few comments and suggestions.

2025-01-23 08:40 UTC, Techassi commented on rust/stackablectl/src/cli/mod.rs
> +impl From<ChartSourceTypeArg> for ChartSourceType {
question: Why do we need this mapping at all? Can't we use `ChartSourceType` directly in the CLI?

2025-01-23 08:40 UTC, Techassi commented on rust/stackablectl/src/cmds/demo.rs
> +    chart_source: ChartSourceTypeArg,
suggestion: Add a doc comment here (short and long help), put attribute arguments on individual lines and drop the mention of Nexus.

```suggestion

    /// Source the charts from either a OCI registry or from index.yaml-based repositories.
    #[arg(
        long,
        value_enum,
        default_value_t = Default::default()
    )]
    chart_source: ChartSourceTypeArg,
```

2025-01-23 08:40 UTC, Techassi commented on rust/stackablectl/src/cli/mod.rs
> +    /// Nexus repositories: resolution (dev, test, stable) is based on the version and thus will be operator-specific
suggestion: Drop the term "Nexus" and replace it with "index.yaml-based". The "old" Helm repositories are _not_ related to Nexus, but instead use a webserver which serves the `index.yaml` file listing available charts.

2025-01-23 08:40 UTC, Techassi commented on rust/stackablectl/src/cmds/demo.rs
> +    chart_source: ChartSourceTypeArg,
idea: Also, it might make sense to move this argument out of individual commands to `CommonRepoArgs` instead.

2025-01-23 08:40 UTC, Techassi commented on rust/stackable-cockpit/src/oci.rs
idea: Does it maybe make sense to unifiy this file with `helm.rs` into one helm module? Something like:

```
helm
  mod.rs
  oci.rs
  ...
```

2025-01-23 08:40 UTC, Techassi commented on rust/stackablectl/src/cmds/operator.rs
> +    chart_source: ChartSourceTypeArg,
note: Same comment from above applies here as well.

2025-01-23 08:40 UTC, Techassi commented on rust/stackablectl/src/cmds/operator.rs
> +    chart_source: ChartSourceTypeArg,
note: Same comment from above applies here as well.

2025-01-23 08:40 UTC, Techassi commented on rust/stackablectl/src/cmds/operator.rs
> +    chart_source: ChartSourceTypeArg,
note: Same comment from above applies here as well.

2025-01-23 08:40 UTC, Techassi commented on rust/stackablectl/src/cmds/operator.rs
> +    OciError { source: oci::Error },
note: I feel like this should be part of `helm::Error`. Internally, this can still be an OCI-specific error enum.

2025-01-23 08:40 UTC, Techassi commented on rust/stackablectl/src/cmds/release.rs
> +    chart_source: ChartSourceTypeArg,
note: Same comment from above applies here as well.

2025-01-23 08:40 UTC, Techassi commented on rust/stackablectl/src/cmds/stack.rs
> +    chart_source: ChartSourceTypeArg,
note: Same comment from above applies here as well.

2025-01-23 08:40 UTC, Techassi commented on rust/stackable-cockpit/src/oci.rs
> +        }
suggestion: Move this into a `loop` for better readability.

```suggestion
        loop {
            let url = format!(
                "{}/projects/{}/repositories/{}/artifacts?page_size={}&page={}",
                base_url,
                encode(project_name),
                encode(repository_name),
                page_size,
                page
            );

            let artifact_page = client
                .get(url)
                .send()
                .await
                .context(GetArtifactsSnafu)?
                .json::<Vec<Artifact>>()
                .await
                .context(ParseArtifactsSnafu)?;
            
            let count = artifacts_page.len();
            artifacts.extend(artifacts_page);
            if count < page_size {
                break;
            }
            page += 1;
        }
```

2025-01-23 08:40 UTC, Techassi commented on rust/stackable-cockpit/src/oci.rs
> +            ))
idea: It might also make sense to abstract constructing these URLs away into a `OciUrlExt` trait and implementing it on `url::Url`, eg: `Url::oci_artifacts_page(...)`.

2025-01-23 08:40 UTC, Techassi commented on rust/stackable-cockpit/src/oci.rs
> +}
note: Please add doc comments for these "model" structs and shorty mention what they are describing. Maybe also add a small excerpt of the JSON they are deserializing from.

2025-01-23 08:40 UTC, Techassi commented on rust/stackable-cockpit/src/platform/manifests.rs
> +                    // Assumption: that all manifest helm charts refer to repos not registries
note: It might make sense to revisit this feature in the future and unify the handling of helm operations independent of OCI registries or index.yaml-based repositories.

2025-01-23 08:40 UTC, Techassi commented on rust/stackable-cockpit/src/oci.rs
> +        let page_size = 20;
note: It might make sense to move this into a constant, because the value never changes. It is only used to construct the URL and to compare page sizes in the following loop.

2025-01-23 08:40 UTC, Techassi commented on rust/stackable-cockpit/src/oci.rs
idea: Maybe all Helm-related functions could be moved into a `HelmClient` which internally handles all the hard stuff while presenting a simple API to the outside, like: `client.install_release(...)`.

2025-01-23 10:19 UTC, adwk67 commented on rust/stackablectl/src/cmds/stack.rs
> +    chart_source: ChartSourceTypeArg,
d4e3b32

2025-01-23 10:19 UTC, adwk67 commented on rust/stackablectl/src/cmds/release.rs
> +    chart_source: ChartSourceTypeArg,
d4e3b32

2025-01-23 10:19 UTC, adwk67 commented on rust/stackablectl/src/cmds/operator.rs
> +    chart_source: ChartSourceTypeArg,
d4e3b32

2025-01-23 10:20 UTC, adwk67 commented on rust/stackablectl/src/cmds/operator.rs
> +    chart_source: ChartSourceTypeArg,
d4e3b32

2025-01-23 10:20 UTC, adwk67 commented on rust/stackablectl/src/cmds/operator.rs
> +    chart_source: ChartSourceTypeArg,
d4e3b32

2025-01-23 10:20 UTC, adwk67 commented on rust/stackablectl/src/cli/mod.rs
> +    /// Nexus repositories: resolution (dev, test, stable) is based on the version and thus will be operator-specific
d4e3b32

2025-01-23 10:52 UTC, adwk67 commented on rust/stackable-cockpit/src/platform/manifests.rs
> +                    // Assumption: that all manifest helm charts refer to repos not registries
Yes, this is out of scope right now but may well be necessary in the future - along with the ability to address a further options with e.g. .tgz charts.

2025-01-23 11:58 UTC, adwk67 commented on rust/stackable-cockpit/src/oci.rs
> +        let page_size = 20;
dce1320

2025-01-23 11:58 UTC, adwk67 commented on rust/stackable-cockpit/src/oci.rs
> +}
dce1320

2025-01-23 15:18 UTC, adwk67 commented on rust/stackable-cockpit/src/oci.rs
> +            ))
c879f3f

2025-01-23 16:38 UTC, adwk67 commented on rust/stackablectl/src/cmds/demo.rs
> +    chart_source: ChartSourceTypeArg,
The `CommonRepoArgs` are always displayed, even though they are not always relevant (e.g. when uninstalling operators). I only included `ChartSourceTypeArg` where it is actually used.

2025-01-23 16:47 UTC, adwk67 commented on rust/stackablectl/src/cli/mod.rs
> +impl From<ChartSourceTypeArg> for ChartSourceType {
We need the derive macro `ValueEnum` and that would mean including the clap crates in stackable-cockpit. What do you think?

2025-01-23 16:48 UTC, adwk67 commented on rust/stackablectl/src/cmds/operator.rs
> +    OciError { source: oci::Error },
Tried. Failed :(

2025-01-23 16:49 UTC, adwk67 commented on rust/stackable-cockpit/src/oci.rs
I think it makes sense. Shall we open a new issue for this?

2025-01-24 10:13 UTC, adwk67 commented on rust/stackablectl/src/cli/mod.rs
> +impl From<ChartSourceTypeArg> for ChartSourceType {
As agreed, we'll leave this as it is and add a comment in code as to the reason.

2025-01-24 10:53 UTC, adwk67 commented on rust/stackable-cockpit/src/oci.rs
New issue: https://github.com/stackabletech/stackable-cockpit/issues/347

2025-01-24 10:54 UTC, adwk67 commented on rust/stackablectl/src/cmds/operator.rs
> +    OciError { source: oci::Error },
As discussed, we'll address this here: https://github.com/stackabletech/stackable-cockpit/issues/347

2025-01-24 10:58 UTC, adwk67 commented on rust/stackablectl/src/cli/mod.rs
> +impl From<ChartSourceTypeArg> for ChartSourceType {
See 1e6947e

2025-01-24 13:27 UTC, adwk67 commented on rust/stackablectl/src/cmds/demo.rs
> +    chart_source: ChartSourceTypeArg,
See 32564c3

2025-01-27 12:56 UTC, Techassi approved these changes

2025-01-27 12:58 UTC, merged