Implement stacks and services commands
stackabletech/stackablectl pull request #36
Opened 2022-06-17 13:02 UTC by sbernauer

This PR adds two new subcommands:
* Stacks to install ready-to-use product sets
* Services which allows users to list and access the running services (https://github.com/stackabletech/stackablectl/issues/10)

The structure of the `stacks.yaml` still needs to be discussed with @lfrancke and might be adopted to the porter.yaml style.
Listing of services is a mechanism i came up with, so is ready to review as is :)

To test the stack command run
```
cargo r -- --additional-release-files releases.yaml --additional-stack-files stacks.yaml stack install druid-superset-s3 -k
```
To test the listing of services (this command was run after installing the stack `druid-superset-s3` and a bunch of other products)
```
cargo r -- services ls 
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/stackablectl services ls`
PRODUCT      NAME                                     NAMESPACE                      ENDPOINTS                                          EXTRA INFOS
airflow      airflow                                  default                        webserver-airflow:   http://172.18.0.4:31206       Admin user: airflow, password: airflow
druid        druid                                    default                        router-http:         http://172.18.0.4:32126       
                                                                                     coordinator-http:    http://172.18.0.4:30347       
hbase        simple-hbase                             default                        regionserver:        172.18.0.4:32413              
                                                                                     ui:                  http://172.18.0.4:32051       
                                                                                     metrics:             172.18.0.4:30504              
hdfs         simple-hdfs                              default                        datanode-default-0-metrics: 172.18.0.4:32607       
                                                                                     datanode-default-0-data: 172.18.0.4:30655          
                                                                                     datanode-default-0-http: http://172.18.0.4:32340   
                                                                                     datanode-default-0-ipc: 172.18.0.4:31295           
                                                                                     namenode-default-0-metrics: 172.18.0.3:31541       
                                                                                     namenode-default-0-http: http://172.18.0.3:31669   
                                                                                     namenode-default-0-rpc: 172.18.0.3:32286           
                                                                                     journalnode-default-0-metrics: 172.18.0.5:30631    
                                                                                     journalnode-default-0-http: http://172.18.0.5:31961 
                                                                                     journalnode-default-0-https: https://172.18.0.5:30133 
                                                                                     journalnode-default-0-rpc: 172.18.0.5:31222        
hive         simple-hive-derby                        default                        hive:                172.18.0.4:30560              
                                                                                     metrics:             172.18.0.4:31796              
superset     superset                                 default                        external-superset:   http://172.18.0.3:30067       Admin user: admin, password: admin
trino        simple-trino                             default                        coordinator-http:    http://172.18.0.5:31395       
                                                                                     coordinator-metrics: 172.18.0.5:32214              
zookeeper    druid-zookeeper                          default                        zk:                  172.18.0.3:32220              
zookeeper    simple-zk                                default                        zk:                  172.18.0.5:32548              
minio        minio-druid                              default                        http:                http://172.18.0.5:30054       Third party service
                                                                                     console-http:        http://172.18.0.5:31771       Admin user: root, password: rootroot
```

2022-06-21 06:28 UTC, sbernauer commented
Build now works again. I have reverted building a static binary as it caused segfaults on Ubuntu 22.04 and Arch

2022-07-21 13:09 UTC, siegfriedweber requested changes
This pull request is very large. I glanced over all changes but a more thorough review is still required.

2022-07-21 13:09 UTC, siegfriedweber commented on src/services.rs
> +async fn list_services(
If services are listed while no cluster is started then the following error is shown:

```
$ cargo run -- services list
Error: InferConfig(InferConfigError { in_cluster: ReadDefaultNamespace(Os { code: 2, kind: NotFound, message: "No such file or directory" }), kubeconfig: InvalidStructure(Message("missing field `clusters`", None)) })
```

This message could be improved.

2022-07-21 13:58 UTC, sbernauer commented on stacks.yaml
> +            # Old version (10) of helm-charts has old way of setting credentials
Sadly hive only works with postgres 10 or older so we can not upgrade (see the note in https://docs.stackable.tech/hive/stable/usage.html)
I may be possible to use a newer helm-chart version and somehow specify an older postgres version but his approach follows the way we did it in the integration-tests

2022-07-21 14:16 UTC, siegfriedweber commented on stacks.yaml
> +            # Old version (10) of helm-charts has old way of setting credentials
okay

2022-07-21 14:25 UTC, sbernauer commented
Thanks for your extensive review!

2022-07-21 14:29 UTC, sbernauer commented on docs/modules/ROOT/pages/commands/operator.adoc
> +secret                0.6.0-nightly   default                        deployed         2022-07-15 09:44:13.526843785 +0200 CEST
I would expect that the larger part of the users is installing the latest version. So it let the "default-flow" go through installing the latest and not fixed versions, hence this output.
I added the following sentence below, is that also ok?
```
In case you have installed the operators in a specific version, the specific versions will be shown instead of the `*-nightly` versions.
```

2022-07-21 14:29 UTC, sbernauer commented on src/arguments.rs
> +    /// This EXPERIMENTAL subcommand interacts with stacks, which are ready-to-use combinations of products.
Lars wanted this disclaimer until the porter discussion was finished. I removed it.

2022-07-21 14:29 UTC, sbernauer commented on docs/modules/ROOT/pages/commands/release.adoc
> +To uninstall the release again you can use the uninstall command
`stackablectl` only allows a single instance of an specific operator to run at a time (unless to trick it by deploying in different namespaces - which generates a warning).
So here it simply removes all the operators that are part of the release - regardless of their version

2022-07-21 14:37 UTC, sbernauer commented on docs/modules/ROOT/pages/customizability.adoc
> +After creating the `mycorp-demos.yaml` file it can be added to the available demos in `stackablectl` via the CLI argument `--additional-demo-files <ADDITIONAL_DEMO_FILES>`.
Yep, having an env variable or some sort of `~/.stackable_config` config file would be very great. As this PR is already very large I added a dedicated Ticket for that: https://github.com/stackabletech/stackablectl/issues/59

The argument `--additional-demo-files` can be specified multiply times, e.g. `--additional-demo-files demo1.yaml --additional-demo-files demo2.yaml`
I tried to find a misleading section in the docs but i wasn't able to find it, would it be possible to please send a link if you find it again?

Sure, updated the example to the introduced file

2022-07-22 07:04 UTC, sbernauer commented on docs/modules/ROOT/pages/commands/services.adoc
> +Currently you can only get a read-only view of the running services, future versions may allow to e.g. uninstall running services.
Here with `service` an deployed product is meant, not a k8s service.
This matches the terminology of this command (`services list`) which does list the installed services/products/deployments whatever you want to call them.
The possible idea would be that users can delete the CRs like `druidclusters.stackable.tech/my-druid`

2022-07-22 07:09 UTC, sbernauer commented on docs/modules/ROOT/pages/commands/services.adoc
> +- Redact the passwords from the output in case you want to share the list of services without giving out the admin credentials
We spoke about it briefly but i we didn't make a decision (at least not with me ^^)
I would vote for printing them by default as i have used the `svc ls` often times during building integration-tests and demos and i really like the ease of clicking on the link and having the .e.g. randomly generated MinIO credentials already there using default settings.
Especially as stackablectl offers the stacks and demos functionality which is especially helpful for beginners, I can image that there are more invokes of `svc ls` which want the credentials printed (e.g. for demos), than users that want to list the services but not print the credentials.
But also always absolutely happy to discuss this in more detail :)

2022-07-22 10:53 UTC, sbernauer commented on docs/modules/ROOT/pages/customizability.adoc
> +== How to add a new
I assume you refer to the section titles. I reworked them

2022-07-22 13:35 UTC, sbernauer commented on src/services.rs
> +pub fn get_service_names(product_name: &str, product: &str) -> Vec<String> {
We have an owner-reference
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-07-22T11:47:17Z"
  labels:
    app.kubernetes.io/component: webserver
    app.kubernetes.io/instance: airflow
    app.kubernetes.io/managed-by: airflow-operator
    app.kubernetes.io/name: airflow
    app.kubernetes.io/role-group: global
    app.kubernetes.io/version: 2.2.5-python39-stackable0.3.0
    statsd-exporter: v0.22.4
  name: airflow-webserver
  namespace: default
  ownerReferences:
  - apiVersion: airflow.stackable.tech/v1alpha1
    controller: true
    kind: AirflowCluster
    name: airflow
    uid: 42eeb6e8-d318-47f8-a15a-a3e165e5ba23
  resourceVersion: "2832"
  uid: d4d1ad48-93e1-411f-ba08-9a7078a6de83
```
Then we may have the task of filtering to all the meaningful services. Maybe filtering to NodePort services is enough, but e.g. for druid I tend to no show all the available services, but only a subset. If the subset is based on the name of the service we again have the problem of hard-coding the service names. I'll have to think about this
```
k get svc | grep airflow
airflow-scheduler-default   ClusterIP   None            <none>        9102/TCP            105m
airflow-webserver           NodePort    10.96.125.158   <none>        8080:30071/TCP      105m
airflow-webserver-default   ClusterIP   None            <none>        9102/TCP,8080/TCP   105m
airflow-worker-default      ClusterIP   None            <none>        9102/TCP            105m
postgresql-airflow          ClusterIP   10.96.136.134   <none>        5432/TCP            112m
postgresql-airflow-hl       ClusterIP   None            <none>        5432/TCP            112m
redis-airflow-headless      ClusterIP   None            <none>        6379/TCP            110m
redis-airflow-master        ClusterIP   10.96.68.33     <none>        6379/TCP            110m
redis-airflow-replicas      ClusterIP   10.96.55.154    <none>        6379/TCP            110m
```

2022-07-25 08:10 UTC, soenkeliebau commented on src/services.rs
> +pub fn get_service_names(product_name: &str, product: &str) -> Vec<String> {
I think we'll have to have some form of marker that allows stackablectl to determine whether or not to expose a service via this functionality. That being said, this is an instance where I'd be willing to accept hard coded stuff as well, as this will always be fairly specific to the products.

2022-07-26 09:21 UTC, siegfriedweber commented on docs/modules/ROOT/pages/customizability.adoc
> +After creating the `mycorp-demos.yaml` file it can be added to the available demos in `stackablectl` via the CLI argument `--additional-demo-files <ADDITIONAL_DEMO_FILES>`.
I meant that only one file can be given per `--additional-demo-files` parameter. Many demos can be specified within one demo file. So it would be more correct to name the parameter `--additional-demos-file`. If multiple demo files are added then the parameters would look like `--additional-demos-file demos1.yaml --additional-demos-file demos2.yaml`. The same goes for the parameter `--additional-stack-files`. It would also be okay for me to name the parameters `--additional-demo-file` and `--additional-stack-file`. But the suffix `files` is misleading.

2022-07-26 09:37 UTC, siegfriedweber commented on docs/modules/ROOT/pages/commands/operator.adoc
> +secret                0.6.0-nightly   default                        deployed         2022-07-15 09:44:13.526843785 +0200 CEST
I thought that this documentation is tutorial-like but it is not. So your comment is sufficient.

2022-07-26 09:46 UTC, siegfriedweber commented on docs/modules/ROOT/pages/commands/release.adoc
> +To uninstall the release again you can use the uninstall command
So this could be rephrased more accurately with

```suggestion
To uninstall all operators contained in a release regardless of their actual installed versions, you can use the uninstall command:
```

or something similar.

2022-07-26 10:27 UTC, siegfriedweber commented on docs/modules/ROOT/pages/commands/services.adoc
> +Currently you can only get a read-only view of the running services, future versions may allow to e.g. uninstall running services.
I read the pull request (and therefore the documentation) from "top to bottom". At this point it was not clear to me that `stackable services list` lists the custom resources enriched with the data from the Kubernetes services. I thought that the running Kubernetes services are listed.

The term "service" was also not introduced before. The documentation page of stackablectl describes Stacks as follows:
> A stack is a collection of ready-to-use Stackable data products as well as needed third-party services like Postgresql or MinIO.

If it would describe it like "A stack is a set of services ..." or better "A stack is a set of Stackable services ..." then the term "service" or "Stackable service" would be defined.

Alternatively, the command could be renamed to `products`:
```
stackablectl products list
```

Then it would follow the ubiquitous language of the company.

2022-07-26 10:29 UTC, siegfriedweber commented on docs/modules/ROOT/pages/commands/services.adoc
> +- Redact the passwords from the output in case you want to share the list of services without giving out the admin credentials
I want to forward this discussion to our product area owners @lfrancke and @soenkeliebau.

2022-07-26 10:41 UTC, siegfriedweber commented on docs/modules/ROOT/pages/commands/stack.adoc
> +A stack is a collection of ready-to-use Stackable data products as well as needed third-party services like Postgresql or MinIO.
To be more precise: A stack is tied to a specific release. The release version is set in the `stackableRelease` field in the stacks file. It should be mentioned here that a stack consists of Stackable products, third-party products, **and** a Stackable release version.

2022-07-26 11:15 UTC, sbernauer commented on docs/modules/ROOT/pages/customizability.adoc
> +After creating the `mycorp-demos.yaml` file it can be added to the available demos in `stackablectl` via the CLI argument `--additional-demo-files <ADDITIONAL_DEMO_FILES>`.
Ah i agree to rename them to `--additional-demos-file` (and similar)
I will do so after merging https://github.com/stackabletech/stackablectl/pull/54

2022-07-26 12:03 UTC, siegfriedweber commented on src/services.rs
> +pub fn get_service_names(product_name: &str, product: &str) -> Vec<String> {
I was confused about the term "service". It is used for the custom resources of Stackable, the deployed Stackable products, as well as the Kubernetes services. For instance, `services::get_stackable_services` returns the deployed custom resources even if the product is not installed. `services::get_service_names` returns the expected name of a Kubernetes service independent of a deployment. `stackablectl services list --output yaml` prints all Stackable CRDs with the CRs if deployed and a subset of the Kubernetes services if deployed.

With this realization, I want to rephrase my comment: I can live with hard-coded product specific knowledge in `stackablectl`. But in my opinion `stackablectl` should only be a convenience wrapper for helm and kubectl and therefore knowledge should be stored as much as possible in the Kubernetes objects (by labelling them accordingly or using a defined schema for secrets and so on).

2022-07-26 12:03 UTC, siegfriedweber commented on src/services.rs
> +    pub static ref STACKABLE_PRODUCT_CRDS: IndexMap<&'static str, GroupVersionKind> =
Resolved because the same discussion is already ongoing in another comment.

2022-07-26 12:07 UTC, siegfriedweber commented on src/services.rs
> +            println!("PRODUCT      NAME                                     NAMESPACE                      ENDPOINTS                                          EXTRA INFOS");
> This requires a wide terminal window. It could be narrowed down if the columns are dynamically sized.

The readability of the code would be improved if the logic of displaying a (generic) table was extracted into a separate module.

> Furthermore, the EXTRA INFOS could only be shown when an according parameter is set.

This is already discussed in another comment.

2022-07-28 09:24 UTC, sbernauer commented on src/main.rs
> +    pub static ref NAMESPACE: Mutex<String> = Mutex::new(String::new());
I honestly don't know. My goal was to avoid passing the namespace around for multiple functions but instead make it a global variable. For that i found https://stackoverflow.com/questions/27791532/how-do-i-create-a-global-mutable-singleton

2022-07-28 09:31 UTC, sbernauer commented on docs/modules/ROOT/pages/commands/stack.adoc
> +A stack is a collection of ready-to-use Stackable data products as well as needed third-party services like Postgresql or MinIO.
I added the sentence `It is tied to a specific release of the Stackable Data Platform, which will provide the needed operators for the Stack.`

2022-07-28 09:34 UTC, sbernauer commented on docs/modules/ROOT/pages/customizability.adoc
> +After creating the `mycorp-demos.yaml` file it can be added to the available demos in `stackablectl` via the CLI argument `--additional-demo-files <ADDITIONAL_DEMO_FILES>`.
Renamed them to additional_releases_file and additional_stacks_file

2022-07-28 10:18 UTC, sbernauer commented on stacks/druid-superset-s3/superset.yaml
> +  loadExamplesOnInit: true
My tough-process was: Enabling the examples improves the users experience as he can look at some provided Dashboards and see what's possible with Superset.
They should belong to the demo, but i don't see an easy way of loading the examples from a demo.
So for me currently the question is whether to remove them entirely, which i personally wouldn't do

2022-07-28 14:33 UTC, siegfriedweber commented on stacks/druid-superset-s3/superset.yaml
> +  loadExamplesOnInit: true
At the moment, stackablectl is mainly used by developers to test the Stackable platform. There it is convenient to have some example data to play around. But as far as I understood, it should be also a tool which is used to setup a production environment. If I deploy a stack to production, I do not want the examples.

When I installed the trino-taxi-data demo, I was overwhelmed by the number of dashboards and charts. I could find everything except the taxi data because Trino was not connected. So even in the demo case, I want to see the data provided by the demo and not necessarily the Superset examples.

2022-07-28 14:42 UTC, siegfriedweber commented on src/main.rs
> +    pub static ref NAMESPACE: Mutex<String> = Mutex::new(String::new());
I agree with the answer in the mentioned Stack Overflow question:
> Avoid global state in general.

However, if you want to implement it this way then it is okay for me.

2022-07-28 14:46 UTC, siegfriedweber commented on src/services.rs
> +            println!("PRODUCT      NAME                                     NAMESPACE                      ENDPOINTS                                          EXTRA INFOS");
Yes, this looks much better. It could be even improved if some borders and separators are removed.

2022-07-29 11:40 UTC, sbernauer commented on src/services.rs
> +            println!("PRODUCT      NAME                                     NAMESPACE                      ENDPOINTS                                          EXTRA INFOS");
I tried my best and ended up with
```
 PRODUCT   NAME         NAMESPACE  ENDPOINTS                                     EXTRA INFOS                          
                                                                                                                      
 hive      hive         default    hive                172.18.0.2:30360                                               
                                   metrics             172.18.0.2:31527                                               
                                                                                                                      
 opa       opa          default    http                http://172.18.0.5:30990                                        
                                                                                                                      
 superset  superset     default    external-superset   http://172.18.0.2:30017   Admin user: admin, password: admin   
                                                                                                                      
 trino     trino        default    coordinator-http    http://172.18.0.2:30178                                        
                                   coordinator-metrics 172.18.0.2:30656                                               
                                   coordinator-https   https://172.18.0.2:30499                                       
                                                                                                                      
 minio     minio-trino  default    http                http://172.18.0.5:30210   Third party service                  
                                   console-http        http://172.18.0.5:31225   Admin user: root, password: rootroot                                   ```

2022-07-29 11:58 UTC, sbernauer commented on docs/modules/ROOT/pages/commands/services.adoc
> +Currently you can only get a read-only view of the running services, future versions may allow to e.g. uninstall running services.
Forwarded the naming question stackablectl services list / stackablectl products list to Sönke and Lars

2022-07-29 12:04 UTC, sbernauer commented on stacks/druid-superset-s3/superset.yaml
> +  loadExamplesOnInit: true
We excluded the production-readiness from the stacks and demo functionality (at least for now). The can serve as a good starting-point but mostly for getting started/prototyping.
The trino-superset demo is not finished yet, so you could not see a Demo Dashboard with taxi data (especially the missing CRD connection trino <-> superset is blocking us)
I think the benefit of having additional Dashboards to see what Superset is capable of outweighs the downside of ignoring Dashboards you are not interested in

2022-07-29 12:15 UTC, sbernauer commented on src/stack.rs
> +            exit(1);
done

2022-07-29 12:15 UTC, sbernauer commented on stacks/trino-superset-s3/superset.yaml
> +  loadExamplesOnInit: true
Discussing in https://github.com/stackabletech/stackablectl/pull/36#discussion_r926580349

2022-07-29 12:50 UTC, lfrancke commented on docs/modules/ROOT/pages/commands/services.adoc
> +- Redact the passwords from the output in case you want to share the list of services without giving out the admin credentials
I assume that the feature will not be super useful in production scenarios as we won't be able to get credentials there anyway.

So, I'm fine either way. I can toss a coin but we can always change it later if needed.
If I had implemented it I would have made it opt-in (security by default).

2022-07-29 12:56 UTC, lfrancke commented on docs/modules/ROOT/pages/commands/services.adoc
> +- Redact the passwords from the output in case you want to share the list of services without giving out the admin credentials
To clarify: I'm fine merging this PR with opt-out

2022-07-29 13:11 UTC, sbernauer commented on docs/modules/ROOT/pages/commands/services.adoc
> +Currently you can only get a read-only view of the running services, future versions may allow to e.g. uninstall running services.
Quick chat with them showed that the agreed on `stackablectl services list`for now with the possibility to change that in the future.

2022-08-01 09:37 UTC, sbernauer commented on docs/modules/ROOT/pages/commands/services.adoc
> +Currently you can only get a read-only view of the running services, future versions may allow to e.g. uninstall running services.
Added the following sentences to the docs of the services command

> In this context a (Stackable) service is a running instance of an data product. This is different from the meaning of an kubernetes services, which is an abstract way to expose an application running on a set of pods as a network service.

2022-08-01 09:52 UTC, sbernauer commented on stacks/druid-superset-s3/superset.yaml
> +  loadExamplesOnInit: true
I removed the examples

2022-08-01 10:00 UTC, sbernauer commented on src/services.rs
> +async fn list_services(
I used `map_err` and it now produces the following error
```
[ERROR] Failed to construct kubernetes client: Failed to infer configuration: failed to infer config: in-cluster: (failed to read the default namespace: No such file or directory (os error 2)), kubeconfig: (failed to determine current context)

2022-08-01 13:28 UTC, sbernauer commented on src/services.rs
> +pub fn get_service_names(product_name: &str, product: &str) -> Vec<String> {
I've reworked the relevant code to retrieve the list of services by labels and not by hard-coded names. Works fine!
Most important snippet
```
let service_list_params = ListParams::default()
    .labels(format!("app.kubernetes.io/instance={product_name}").as_str())
    .labels(format!("app.kubernetes.io/name={object_name}").as_str());
let services = service_api.list(&service_list_params).await?;
```

2022-08-01 13:29 UTC, sbernauer commented
I *think* I addressed all review comments. Can you please do another round of review?

2022-08-02 08:52 UTC, sbernauer commented
Feedback from https://github.com/stackabletech/stackablectl/pull/55 adopted into this PR

2022-08-04 07:20 UTC, siegfriedweber requested changes
Documentation reviewed

2022-08-04 07:47 UTC, sbernauer commented on Cargo.toml
> +tokio = "1.19.2"
agreed

2022-08-04 07:55 UTC, sbernauer commented on docs/modules/ROOT/pages/customization.adoc
> +The `<ADDITIONAL_DEMO_FILES>` can be either a path to a file on the local filesystem or a URL.
Changed to:
The argument to `--additional-demos-file` can be either...

2022-08-04 07:57 UTC, sbernauer commented on docs/modules/ROOT/pages/commands/demo.adoc
> +Not implemented yet
Yes, I am. The reason i introduced it already was that I'm able to write about it and create references to the demo command before it actually exists.
The demo change is much smaller than this PR so I'm hoping the state will not last long

2022-08-04 07:59 UTC, sbernauer commented on docs/modules/ROOT/pages/customization.adoc
> +== Add a new demo
Agreed. In this case i followed the rationale behind https://github.com/stackabletech/stackablectl/pull/36#discussion_r937467150

2022-08-04 09:03 UTC, sbernauer commented on docs/modules/ROOT/pages/troubleshooting.adoc
> +| List of demos provided by Stackable
I can see the problem, do you have an idea on how to solve that? Version the release/stacks/demos files? Maybe not mandatory via branches but naming them releases-v1.yaml releases-v2.yaml and bumping the number when we make a breaking change

2022-08-04 09:23 UTC, sbernauer commented on docs/modules/ROOT/pages/customization.adoc
> +In the custom defined Stack all Product versions are pinned as well, so you can easily spin up a Stack containing the exact same versions as your production setup.
I grep-ed through the docs/ folder and made the case consistent

2022-08-04 15:19 UTC, siegfriedweber submitted a review, later dismissed

2022-08-04 15:19 UTC, siegfriedweber commented on src/stack.rs
> +        "https://raw.githubusercontent.com/stackabletech/stackablectl/main/stacks.yaml".to_string(),
If the file is always downloaded from the main branch then breaking changes cannot be introduced without breaking all old clients.

2022-08-04 15:19 UTC, siegfriedweber commented on src/stack.rs
>              println!("STACK                               STACKABLE RELEASE  DESCRIPTION");
`cli-table` could also be used here.

2022-08-04 15:26 UTC, sbernauer commented on src/services.rs
> +    pub static ref STACKABLE_PRODUCT_CRDS: IndexMap<&'static str, GroupVersionKind> =
The reason is the different approach the operators are taking. All the other operators roll out products that run 24/7 until deleted again.
A Spark-Application is more like a k8s job that get's created and shut down after completion.
Maybe we can include Spark Application here in the future but they will need a different way of listing them and their endpoints/infos

2022-08-04 15:42 UTC, sbernauer commented on src/stack.rs
>              println!("STACK                               STACKABLE RELEASE  DESCRIPTION");
For all commands beside `services list` i tried to stick to a similar output as `kubectl`. I only used `cli-table` as the output was very wide and the column should be sided dynamically.
When we change the way of representing here we should change it for all outputs i think. I didn't find a way to represent kubectl-like output with any crate out there

2022-08-04 16:01 UTC, sbernauer commented on src/stack.rs
> +        "https://raw.githubusercontent.com/stackabletech/stackablectl/main/stacks.yaml".to_string(),
As in https://github.com/stackabletech/stackablectl/pull/36#discussion_r935699053 I'm not sure what's the correct way to go

2022-08-04 17:49 UTC, siegfriedweber commented on docs/modules/ROOT/pages/troubleshooting.adoc
> +| List of demos provided by Stackable
Would it be an option to deliver these files together with the `stackablectl` binary? When `stackablectl` is properly packaged and the update is done via a package manager then this could be a viable solution.

If that is not an option then you should version the files somehow.

2022-08-05 14:46 UTC, maltesander reviewed
Not finished yet, will continue on monday

2022-08-05 14:46 UTC, maltesander commented on docs/modules/ROOT/pages/commands/operator.adoc
> +This command only includes the stable versions for every operator to not mess up the whole screen.
```suggestion
This command only includes the stable versions of every operator for clarity.
```

2022-08-05 14:46 UTC, maltesander commented on docs/modules/ROOT/pages/commands/operator.adoc
> +After that run the following command, which will install the operators in their latest version.
I will install the nightly one right?
```suggestion
After that run the following command, which will install the operators in their latest nightly version.
```

2022-08-05 14:46 UTC, maltesander commented on docs/modules/ROOT/pages/commands/release.adoc
> +A release is a well-playing bundle of operators.
```suggestion
A release is a bundle of operators of a specific stable version. The stable versions of the operators are tested and proven to work hand in hand.
```

2022-08-05 14:46 UTC, maltesander commented on docs/modules/ROOT/pages/commands/stack.adoc
> +A stack is a collection of ready-to-use Stackable data products as well as needed third-party services like Postgresql or MinIO.
```suggestion
A stack is a collection of ready-to-use Stackable data products as well as required third-party services like Postgresql or MinIO.
```

2022-08-05 14:46 UTC, maltesander commented on docs/modules/ROOT/pages/commands/stack.adoc
> +It is tied to a specific release of the Stackable Data Platform, which will provide the needed operators for the Stack.
I know its kind of a synonym but i feel require fits better.
```suggestion
It is tied to a specific release of the Stackable Data Platform, which will provide the required operators for the Stack.
```

2022-08-05 14:46 UTC, maltesander commented on docs/modules/ROOT/pages/commands/stack.adoc
> +$ stackablectl stack list
I get a warning and no stacks if i run this?
```
[WARN ] Failed to parse stack list from https://raw.githubusercontent.com/stackabletech/stackablectl/main/stacks.yaml: stacks.trino-superset: missing field `labels` at line 4 column 16
STACK                               STACKABLE RELEASE  DESCRIPTION

```

2022-08-05 14:46 UTC, maltesander commented on docs/modules/ROOT/pages/commands/stack.adoc
> +Maybe a solution would be to uninstall the components of the stack but leave the release running.
Should this be in here rather than an issue?

2022-08-05 14:46 UTC, maltesander commented on docs/modules/ROOT/pages/customization.adoc
> +Any additional demos/stacks/releases you specify, will be added to the already existing provided by Stackable.
```suggestion
Any additional demos/stacks/releases you specify, will be added to the already existing ones provided by Stackable.
```

2022-08-05 14:46 UTC, maltesander commented on docs/modules/ROOT/pages/customization.adoc
> +First you must create a `mycorp-demos.yaml` containing demos according to the format defined by https://github.com/stackabletech/stackablectl/blob/main/demos.yaml[the Stackable provided demos].
The link is 404

2022-08-05 14:46 UTC, maltesander commented on docs/modules/ROOT/pages/customization.adoc
> +The argument to `--additional-demos-file` can be either a path to a file on the local filesystem or a URL.
```suggestion
The argument to `--additional-demos-file` can be either a path to a file on the local filesystem or an URL.
```

2022-08-05 14:46 UTC, maltesander commented on docs/modules/ROOT/pages/customization.adoc
> +By using a URL the demos file can be put into a central Git repository and referenced by all teams or clients.
```suggestion
By using an URL the demos file can be put into a central Git repository and referenced by all teams or clients.
```

2022-08-08 06:41 UTC, sbernauer commented on docs/modules/ROOT/pages/commands/operator.adoc
> +After that run the following command, which will install the operators in their latest version.
Yes. But is the term nightly even correct? That's the reason i intentionally left it out)
What do you think of the following?
After that run the following command, which will install the operators in their latest (also called nightly) version.

2022-08-08 06:43 UTC, sbernauer commented on docs/modules/ROOT/pages/commands/stack.adoc
> +$ stackablectl stack list
Yes, that's because this  PR has not been merged into main. The error will go away after merging

2022-08-08 06:45 UTC, sbernauer commented on docs/modules/ROOT/pages/commands/stack.adoc
> +Maybe a solution would be to uninstall the components of the stack but leave the release running.
I think creating an Issue sounds good, but i would leave it here for transparency reasons.
Created https://github.com/stackabletech/stackablectl/issues/64

2022-08-08 06:45 UTC, sbernauer commented on docs/modules/ROOT/pages/customization.adoc
> +First you must create a `mycorp-demos.yaml` containing demos according to the format defined by https://github.com/stackabletech/stackablectl/blob/main/demos.yaml[the Stackable provided demos].
Yes, because the demo PR is not merged yet. When it gets merged it will be there

2022-08-08 07:24 UTC, maltesander reviewed
Some more comments...will do some testing now. I think we need a more automated way to provide the product (e.g. druid-superset-s3) yamls.

2022-08-08 07:26 UTC, maltesander commented on docs/modules/ROOT/pages/commands/operator.adoc
> +After that run the following command, which will install the operators in their latest version.
Yeah sounds good

2022-08-08 14:14 UTC, maltesander commented
Tested and works fine. The only thing i dislike with the service feature are the warnings if not all operators / crds are installed:
```
malte@mdesktop ~/d/w/stackablectl (access-services)> stackablectl svc list
[WARN ] Unsuccessful data error parse: 404 page not found
    
[WARN ] Unsuccessful data error parse: 404 page not found
    
[WARN ] Unsuccessful data error parse: 404 page not found
    
[WARN ] Unsuccessful data error parse: 404 page not found
    
[WARN ] Unsuccessful data error parse: 404 page not found
    
[WARN ] Unsuccessful data error parse: 404 page not found
    
[WARN ] Unsuccessful data error parse: 404 page not found
    
[WARN ] Unsuccessful data error parse: 404 page not found
    
 PRODUCT  NAME  NAMESPACE  ENDPOINTS  EXTRA INFOS 
```
This is coming from kube-rs (https://github.com/kube-rs/kube-rs/issues/949, https://github.com/kube-rs/kube-rs/discussions/948).

In main.rs:
```
#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let args = CliArgs::parse();
    env_logger::builder()
        .format_timestamp(None)
        .format_target(false)
        .filter_level(args.log_level.into())
        .filter(Some("kube_client"), log::LevelFilter::Error)
        .init();
```

2022-08-09 08:42 UTC, sbernauer commented on src/stack.rs
> +        /// If specified, a local Kubernetes cluster consisting of 4 nodes for testing purposes will be created.
Should we rephrase it to "If specified, a local Kubernetes cluster consisting of 4 nodes (1 for control-plane and 3 workers) for testing purposes will be created."?

2022-08-09 08:50 UTC, sbernauer commented on docs/modules/ROOT/pages/commands/operator.adoc
> +After that run the following command, which will install the operators in their latest version.
done

2022-08-09 08:50 UTC, sbernauer commented on docs/modules/ROOT/pages/index.adoc
> +A Kubernetes cluster is required to use the Stackable Data Platform as all products and operators run on Kubernetes.
I think we are not saying a k8s cluster needs Stackable but instead Stackable needs k8s which is correct i guess.

2022-08-09 08:50 UTC, sbernauer commented on go-helm-wrapper/main.go
>  //export go_install_helm_release
Nope, that's required to make the go <-> Rust magic happen

2022-08-09 08:50 UTC, sbernauer commented on src/kube.rs
> +                    // TODO: Consolidate web-ui port names in operators
Added to arch meeting agenda

2022-08-09 08:53 UTC, sbernauer commented on src/services.rs
> +                        .unwrap();
done

2022-08-09 09:15 UTC, sbernauer commented
I think i found a better solution. I'm using discovery to check if the ProductCRD is installed. The `api.list()` will only be executed when the ProductCRD is installed :)

2022-08-09 09:17 UTC, maltesander commented on docs/modules/ROOT/pages/index.adoc
> +A Kubernetes cluster is required to use the Stackable Data Platform as all products and operators run on Kubernetes.
Then i would turn it around (now it says kubernetes requires stackable):
```
The Stackable Data Platform requires a Kubernetes cluster as all products and operators run on Kubernetes.
```

2022-08-09 09:18 UTC, maltesander commented on src/stack.rs
> +        /// If specified, a local Kubernetes cluster consisting of 4 nodes for testing purposes will be created.
Yeah!

2022-08-09 10:19 UTC, sbernauer commented on docs/modules/ROOT/pages/troubleshooting.adoc
> +| List of demos provided by Stackable
Implemented versioning by calling the file `stacks/stacks-v1.yaml` as we i don't think it's a good idea to put it into the binary.

2022-08-09 10:52 UTC, maltesander approved these changes
LGTM.

2022-08-09 10:59 UTC, sbernauer commented
Many thanks to all of you!

2022-08-09 10:59 UTC, sbernauer commented
bors r+

2022-08-09 11:00 UTC, closed without merging