Support generation of shell completions
stackabletech/stackablectl pull request #54
Opened 2022-07-19 09:34 UTC by sbernauer

## Description

This was surprisingly easy. Following the same semantics as `kubectl`.

Docs will be added via the docs-rewrite in https://github.com/stackabletech/stackablectl/pull/36.
We can copy parts of `kubectl` docs

You can try it out with `source <(stackablectl completion bash)` (for bash)

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-07-20 07:19 UTC, sbernauer commented
If you have any installation instructions for your shell  (in addition to https://github.com/stackabletech/stackablectl/commit/c97f6ac8eb1d0efda879b71858f877661d3c212f) please paste them here and i will add them to the docs.

2022-07-20 13:40 UTC, siegfriedweber commented
I tried it with the fish shell. The command and option names are auto-completed but the values are not.

I would have expected that at least the static option values can be completed like `stackablectl --log-level`. But there is no hint what to enter.

It would be great if also the dynamic option values would work. The auto-completion in kubectl is tremendously helpful with that:
```
$ kubectl logs --namespace 
default  kube-node-lease  kube-public  kube-system  local-path-storage

$ kubectl logs --namespace default
commons-operator-deployment-747bbfd76f-8wx7c  secret-operator-daemonset-sj4dn
hbase-operator-deployment-846bfb56d6-z2zdf    secret-operator-daemonset-z454t
hdfs-operator-deployment-69bdd9995c-5rv6v     zookeeper-operator-deployment-5b5b8c5896-hlwtb
secret-operator-daemonset-q5ptw
```

2022-07-21 06:57 UTC, sbernauer commented
Thanks for your review!
I noticed the missing --log-level completion as well, reason being its an external enum we are using. With code-duplication or some Rust magic we can fix this. I will give it a try.
The whole dynamic completion would be awesome but also pretty complicated (you can get an idea [here](https://github.com/clap-rs/clap/issues/1232))
I would suggest merging this with only the static functionality and look into dynamic completion one clap improves support for this.
But feel free to pick this up :)
Is this ok for you?

2022-07-26 07:15 UTC, soenkeliebau commented
The funcitonality in this PR is fine for now, we'll open a follow up ticket for the more fully fledged functionality that also completes release names etc.

2022-07-26 07:36 UTC, sbernauer commented
@siegfriedweber with @soenkeliebau's comments in mind: could you please review the PR again? The --log-level option should work now

2022-07-26 08:39 UTC, siegfriedweber requested changes
The auto-completion generated by clap adds some value but depending on the used shell, the value is limited. For instance, in the fish shell the auto-completion stops working after the first option (`stackablectl -l info -`). The workaround is to discard the spaces on short options (`stackablectl -linfo -`) but this does not work for long options like `--additional-release-files`. However, this works in bash.

2022-07-26 08:39 UTC, siegfriedweber commented on src/arguments.rs
>      pub additional_stack_files: Vec<String>,
In the fish shell, the comments are displayed in one line. Long lines are truncated:

```
$ stackablectl --
--additional-release-files  (If you don't have access to the Stackable GitHub repos or you wa…)
--additional-stack-files  (If you don't have access to the Stackable GitHub repos or you want…)
```

The comments could be shortened or a shorter version could be provided with https://docs.rs/clap/latest/clap/builder/struct.Arg.html#method.help. Alternatively, the comments could start with the important part, e.g. "Adds a YAML file containing custom releases. ..."

2022-07-26 08:39 UTC, siegfriedweber commented on src/arguments.rs
> +    fn from(val: &LogLevel) -> Self {
I would not use pointers for trivial enums. If you also add the `Copy` trait to the enum then it is easier to use:
`args.log_level.into()` instead of `(&args.log_level).into()`.

2022-07-26 10:52 UTC, sbernauer commented on src/arguments.rs
> +    fn from(val: &LogLevel) -> Self {
Thx, good to know!

2022-07-26 11:12 UTC, sbernauer commented on src/arguments.rs
>      pub additional_stack_files: Vec<String>,
Agreed! I added short help texts

2022-07-26 12:42 UTC, siegfriedweber commented on src/arguments.rs
>      pub additional_stack_files: Vec<String>,
Thank you! The descriptions are now readable even on small terminal windows:

```
$ stackablectl --
--additional-release-files  (Adds a YAML file containing custom releases)
--additional-stack-files      (Adds a YAML file containing custom stacks)
--helm-repo-stackable-dev        (Overwrite the URL of the dev helm repo)
--helm-repo-stackable-stable  (Overwrite the URL of the stable helm repo)
--helm-repo-stackable-test      (Overwrite the URL of the test helm repo)
--help                                           (Print help information)
--log-level                                                   (Log level)
--namespace        (Namespace where to deploy the products and operators)
--version                                     (Print version information)
```

2022-07-26 12:43 UTC, siegfriedweber approved these changes

2022-07-28 07:34 UTC, sbernauer commented
Thx!

2022-07-28 07:35 UTC, sbernauer commented
bors r+

2022-07-28 07:35 UTC, closed without merging