Implement demo command
stackabletech/stackablectl pull request #55
Opened 2022-07-20 12:44 UTC by sbernauer

## Description

**This PR diffs against the access-services branch** as it builds on top of the functionality of it.
It adds the demo command which is very similar to the stacks command, just another layer on top.
Use the following commands to test it
```
sbernauer@sbernauer:~/stackabletech/stackablectl$ target/debug/stackablectl --additional-stack-files stacks.yaml  --additional-demo-files demos.yaml demo list
[WARN ] Failed to parse demo list from https://raw.githubusercontent.com/stackabletech/stackablectl/main/demos.yaml: missing field `demos` at line 1 column 4
DEMO                                STACKABLE STACK           DESCRIPTION
trino-taxi-data                     trino-superset-s3         WIP Demo loading NY taxi-data into S3 bucket, creating Trino table and Superset dashboard
trino-wine-reviews                  trino-superset-s3         WIP Demo loading wine review data into S3 bucket, creating Trino table and Superset dashboard

sbernauer@sbernauer:~/stackabletech/stackablectl$ target/debug/stackablectl --additional-stack-files stacks.yaml  --additional-demo-files demos.yaml demo describe trino-taxi-data
[WARN ] Failed to parse demo list from https://raw.githubusercontent.com/stackabletech/stackablectl/main/demos.yaml: missing field `demos` at line 1 column 4
Demo:               trino-taxi-data
Description:        WIP Demo loading NY taxi-data into S3 bucket, creating Trino table and Superset dashboard
Stackable stack:    trino-superset-s3
Labels:             trino, superset, minio, s3, ny-taxi-data

sbernauer@sbernauer:~/stackabletech/stackablectl$ target/debug/stackablectl --additional-stack-files stacks.yaml  --additional-demo-files demos.yaml demo install trino-taxi-data
[INFO ] Installing demo trino-taxi-data
[WARN ] Failed to parse demo list from https://raw.githubusercontent.com/stackabletech/stackablectl/main/demos.yaml: missing field `demos` at line 1 column 4
[INFO ] Installing stack trino-superset-s3
[WARN ] Failed to parse stack list from https://raw.githubusercontent.com/stackabletech/stackablectl/main/stacks.yaml: stacks.trino-superset: missing field `labels` at line 4 column 16
[INFO ] Installing release 22.06
[INFO ] Installing airflow operator in version 0.4.0
[INFO ] The release airflow-operator in version 0.4.0 is already installed, not installing it
[INFO ] Installing commons operator in version 0.2.0
[INFO ] The release commons-operator in version 0.2.0 is already installed, not installing it
[INFO ] Installing druid operator in version 0.6.0
[INFO ] The release druid-operator in version 0.6.0 is already installed, not installing it
[INFO ] Installing hbase operator in version 0.3.0
[INFO ] The release hbase-operator in version 0.3.0 is already installed, not installing it
[INFO ] Installing hdfs operator in version 0.4.0
[INFO ] The release hdfs-operator in version 0.4.0 is already installed, not installing it
[INFO ] Installing hive operator in version 0.6.0
[INFO ] The release hive-operator in version 0.6.0 is already installed, not installing it
[INFO ] Installing kafka operator in version 0.6.0
[INFO ] The release kafka-operator in version 0.6.0 is already installed, not installing it
[INFO ] Installing nifi operator in version 0.6.0
[INFO ] The release nifi-operator in version 0.6.0 is already installed, not installing it
[INFO ] Installing opa operator in version 0.9.0
[INFO ] The release opa-operator in version 0.9.0 is already installed, not installing it
[INFO ] Installing secret operator in version 0.5.0
[INFO ] The release secret-operator in version 0.5.0 is already installed, not installing it
[INFO ] Installing spark-k8s operator in version 0.3.0
[INFO ] The release spark-k8s-operator in version 0.3.0 is already installed, not installing it
[INFO ] Installing superset operator in version 0.5.0
[INFO ] The release superset-operator in version 0.5.0 is already installed, not installing it
[INFO ] Installing trino operator in version 0.4.0
[INFO ] The release trino-operator in version 0.4.0 is already installed, not installing it
[INFO ] Installing zookeeper operator in version 0.10.0
[INFO ] The release zookeeper-operator in version 0.10.0 is already installed, not installing it
[INFO ] Installing components of stack trino-superset-s3
[INFO ] The release minio-trino in version 4.0.5 is already installed, not installing it
[INFO ] The release postgresql-hive in version 10.16.2 is already installed, not installing it
[INFO ] The release postgresql-superset in version 11.0.0 is already installed, not installing it
[INFO ] Installed stack trino-superset-s3
[INFO ] Installing components of demo trino-taxi-data
[INFO ] Installed demo trino-taxi-data. Use "stackablectl services list" to list the installed services
```

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-07-28 09:15 UTC, siegfriedweber requested changes

2022-07-28 09:15 UTC, siegfriedweber commented on demos.yaml
> +  trino-taxi-data:
I tried this demo but was not able to connect Superset to Trino. The following error was displayed in Superset:

```
ERROR: HTTPSConnectionPool(host='trino-coordinator', port=8443): Max retries exceeded with url: /v1/statement (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))
```

It would be great if the demos are documented somewhere.

2022-08-02 07:27 UTC, sbernauer commented on demos.yaml
> +  trino-taxi-data:
Just for the record you need ti put in the following configs
Docs (or even better ConnectionCRD) will be put in when the demo is finished. Currently the demo just loads test-data and create a Table.
![image](https://user-images.githubusercontent.com/29303194/182316877-f5e03f24-bf63-49fc-94bb-510c26755f8d.png)

2022-08-02 08:35 UTC, sbernauer commented on src/arguments.rs
> +    /// Can either be an URL or a path to a file e.g. `https://my.server/my-stacks.yaml`, '/etc/my-stacks.yaml' or `C:\Users\Sebastian\my-stacks.yaml`.
Added to https://github.com/stackabletech/stackablectl/pull/36

2022-08-02 08:36 UTC, sbernauer commented on src/arguments.rs
> +    /// Can either be an URL or a path to a file e.g. `https://my.server/my-demos.yaml`, '/etc/my-demos.yaml' or `C:\Users\Sebastian\my-demos.yaml`.
Added to https://github.com/stackabletech/stackablectl/pull/36

2022-08-02 08:38 UTC, sbernauer commented on src/arguments.rs
> +    /// This command interacts with demos, which are end-to-end demonstrations of the usage of the Stackable Data Platform.
I don't think i will every understand commas in English like wtf
Adopted in https://github.com/stackabletech/stackablectl/pull/36

2022-08-02 08:43 UTC, sbernauer commented on src/demo.rs
> +        /// If specified a local kubernetes cluster consisting of 4 nodes for testing purposes will be created.
Added to https://github.com/stackabletech/stackablectl/pull/36

2022-08-02 08:44 UTC, sbernauer commented on src/demo.rs
> +        /// Kind is a tool to spin up a local kubernetes cluster running on docker on your machine.
Added to https://github.com/stackabletech/stackablectl/pull/36

2022-08-02 08:46 UTC, sbernauer commented on src/demo.rs
> +    demo_files.append(&mut args.additional_demo_files.clone());
Added to https://github.com/stackabletech/stackablectl/pull/36

2022-08-02 08:51 UTC, sbernauer commented on src/demo.rs
> +            for (demo_name, demo) in output.demos.iter() {
Added to https://github.com/stackabletech/stackablectl/pull/36

2022-08-04 17:33 UTC, siegfriedweber commented on src/arguments.rs
> +    /// Can either be an URL or a path to a file e.g. `https://my.server/my-releases.yaml`, '/etc/my-releases.yaml' or `C:\Users\Sebastian\my-releases.yaml`.
Added to #36

2022-08-09 11:00 UTC, closed without merging

2022-08-09 11:05 UTC, sbernauer commented
bors closed this but that's fine
Going to open a new PR to implement demos