Implement demo command
stackabletech/stackablectl pull request #66
Opened 2022-08-09 13:35 UTC by sbernauer

## Description

*Please add a description here. This will become the commit message of the merge request later.*

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-08-09 13:36 UTC, sbernauer commented on demos/demos-v1.yaml
> +      - plainYaml: https://raw.githubusercontent.com/stackabletech/stackablectl/demos/demos/trino-taxi-data/setup-superset.yaml
Change to main branch before merging

2022-08-09 13:36 UTC, sbernauer commented on demos/trino-taxi-data/setup-superset.yaml
> +          command: ["bash", "-c", " apt update && apt install -y curl && curl -o superset-assets.zip https://raw.githubusercontent.com/stackabletech/stackablectl/demos/demos/trino-taxi-data/superset-
Change to main branch before merging

2022-08-10 11:05 UTC, maltesander requested changes
Just one type. Works great!
![image](https://user-images.githubusercontent.com/19609456/183885274-25547b6c-259e-4784-b003-67e115487e60.png)
Just ran in the superset timeout, but nothing we can do about that here.
```
malte@mdesktop ~/d/w/stackablectl (demos) [2]> target/debug/stackablectl demo list
[WARN ] Failed to parse demo list from https://raw.githubusercontent.com/stackabletech/stackablectl/main/demos/demos-v1.yaml: missing field `demos` at line 1 column 4
DEMO                                STACKABLE STACK           DESCRIPTION
malte@mdesktop ~/d/w/stackablectl (demos)> target/debug/stackablectl demo describe trino-taxi-data
[WARN ] Failed to parse demo list from https://raw.githubusercontent.com/stackabletech/stackablectl/main/demos/demos-v1.yaml: missing field `demos` at line 1 column 4
[ERROR] Demo trino-taxi-data not found. Use `stackablectl demo list` to list the available demos.
malte@mdesktop ~/d/w/stackablectl (demos) [255]> 
```
The list and describe do not work for me?

2022-08-10 12:07 UTC, sbernauer commented on docs/modules/ROOT/pages/commands/demo.adoc
> +$ stackablectl demos list
fixed, thx

2022-08-10 12:08 UTC, sbernauer commented
As this PR is not merged you have to specify the additional demos file like
`cargo r -- --additional-demos-file demos/demos-v1.yaml demo list`
`cargo r -- --additional-demos-file demos/demos-v1.yaml demo describe trino-taxi-data`

2022-08-10 12:21 UTC, maltesander approved these changes
LGTM.

2022-08-10 15:13 UTC, sbernauer commented
@maltesander could you please also review the new docs?
I think it's a good idea to document any demo, so i created a sub-folder for them.

2022-08-10 16:48 UTC, maltesander requested changes
I like it but im not sure about the detail of the description. It feels a lot of it could e.g. be in the superset docs (the story about how many passengers, invalid records, views etc.)

2022-08-10 16:48 UTC, maltesander commented on docs/modules/ROOT/pages/commands/demo.adoc
> +trino-taxi-data                     trino-superset-s3         Demo loading 2 years of New York taxi data into S3 bucket, creating Trino table and Superset dashboard
Did not test it but i think the demo link will be shown here in the description?

```suggestion
trino-taxi-data                     trino-superset-s3         Demo loading 2 years of New York taxi data into S3 bucket, creating Trino table and Superset dashboard. Documentation: https://docs.stackable.tech/stackablectl/stable/demos/trino-taxi-data.html```

2022-08-10 16:48 UTC, maltesander commented on docs/modules/ROOT/pages/commands/demo.adoc
> +Description:        Demo loading 2 years of New York taxi data into S3 bucket, creating Trino table and Superset dashboard
```suggestion
Description:        Demo loading 2 years of New York taxi data into S3 bucket, creating Trino table and Superset dashboard. Documentation: https://docs.stackable.tech/stackablectl/stable/demos/trino-taxi-data.html
```

2022-08-10 16:48 UTC, maltesander commented on docs/modules/ROOT/pages/demos/trino-taxi-data.adoc
> +* Install the needed Stackable operators
```suggestion
* Install the required Stackable operators
```

2022-08-10 16:48 UTC, maltesander commented on docs/modules/ROOT/pages/demos/trino-taxi-data.adoc
> +** MinIO: A S3 compatible object store. This demo uses it as long-term storage.
Not sure about this one :D
```suggestion
** MinIO: A S3 compatible object store. This demo uses it as persistent storage.
```

2022-08-10 16:48 UTC, maltesander commented on docs/modules/ROOT/pages/demos/trino-taxi-data.adoc
> +* Load testdata into S3. It contains 2 and a half years of New York City taxi trips.
I would go for either both text or both numbers
```suggestion
* Load testdata into S3. It contains 2.5 years of New York City taxi trips.
```

2022-08-10 16:48 UTC, maltesander commented on docs/modules/ROOT/pages/demos/trino-taxi-data.adoc
> +The S3 provided by MinIO provides long-term storage.
If you adapt the persistent above, keep it consistent here. I never really heard of long-term storage.

2022-08-10 16:48 UTC, maltesander commented on docs/modules/ROOT/pages/demos/trino-taxi-data.adoc
> +The demo loaded 2 and a half years of taxi trip data from New York City with 68 million records and a total size of 1GB in parquet files.
```suggestion
The demo loaded 2.5 years of taxi trip data from New York City with 68 million records and a total size of 1GB in parquet files.
```

2022-08-10 16:48 UTC, maltesander commented on docs/modules/ROOT/pages/demos/trino-taxi-data.adoc
> +This probably is a invalid record.
```suggestion
This probably is an invalid record.
```

2022-08-10 16:48 UTC, maltesander commented on docs/modules/ROOT/pages/quickstart.adoc
> +trino-taxi-data                     trino-superset-s3         Demo loading 2 years of New York taxi data into S3 bucket, creating Trino table and Superset dashboard
Description change should be reflected here

2022-08-11 06:17 UTC, sbernauer commented
I moved the documentation to a separate (optional) field so it's machine-readable. I don't think we want to print the docs link when listing the demos, what do you think?
```
$ cargo r -- --additional-demos-file demos/demos-v1.yaml demo list
DEMO                                STACKABLE STACK           DESCRIPTION
trino-taxi-data                     trino-superset-s3         Demo loading 2 years of New York taxi data into S3 bucket, creating Trino table and Superset dashboard
$ cargo r -- --additional-demos-file demos/demos-v1.yaml demo describe trino-taxi-data
Demo:               trino-taxi-data
Description:        Demo loading 2 years of New York taxi data into S3 bucket, creating Trino table and Superset dashboard
Documentation:      https://docs.stackable.tech/stackablectl/stable/demos/trino-taxi-data.html
Stackable stack:    trino-superset-s3
Labels:             trino, superset, minio, s3, ny-taxi-data
```

2022-08-11 06:19 UTC, sbernauer commented on docs/modules/ROOT/pages/demos/trino-taxi-data.adoc
> +** MinIO: A S3 compatible object store. This demo uses it as long-term storage.
Changed to `** MinIO: A S3 compatible object store. This demo uses it as a persistent storage to store all the data used`

2022-08-11 06:20 UTC, sbernauer commented on docs/modules/ROOT/pages/demos/trino-taxi-data.adoc
> +The S3 provided by MinIO provides long-term storage.
Changed to `The S3 provided by MinIO is used as persistent storage to store all the data used`

2022-08-11 06:24 UTC, sbernauer commented
Thanks @maltesander, comments should be addressed.
Regarding the level of detail: I plan to document all the demos this way as i don't assume any(or not much) knowledge of the users. The `(the story about how many passengers, invalid records, views etc.)` is for me bound to this specific datasets and in turn to this specific demo. I'm planning on adding a similar demo with other data, maybe real-time data with druid. The the analysis  in Superset will be a different story.
Anyway it might be a good idea to mention and link to the demos out there using Superset. Something like "If you'd like to see Superset i action check out this demos: [.,..]". But I'm hoping that demos will be more present in the future and some sort of an entry-point for the users ;)

2022-08-11 08:24 UTC, maltesander commented
> Thanks @maltesander, comments should be addressed. Regarding the level of detail: I plan to document all the demos this way as i don't assume any(or not much) knowledge of the users. The `(the story about how many passengers, invalid records, views etc.)` is for me bound to this specific datasets and in turn to this specific demo. I'm planning on adding a similar demo with other data, maybe real-time data with druid. Then the analysis in Superset will be a different story. Anyway it might be a good idea to mention and link to the demos out there using Superset. Something like "If you'd like to see Superset i action check out this demos: [.,..]". But I'm hoping that demos will be more present in the future and some sort of an entry-point for the users ;)

Ok yeah related to the demo data that makes sense then for me. One more thing: 
In the `stackablectl demo describe` examples in the docs the "documentation" field does not show up yet?

2022-08-11 08:38 UTC, sbernauer commented
Oh noes, missed that. Added now

2022-08-11 08:49 UTC, maltesander approved these changes
Nice! LGTM.

2022-08-11 08:51 UTC, sbernauer commented
Thanks a lot for your very fast review!

2022-08-11 08:51 UTC, sbernauer commented
bors r+

2022-08-11 08:52 UTC, closed without merging