Demo kafa druid earthquake data
stackabletech/stackablectl pull request #72
Opened 2022-08-15 11:39 UTC by sbernauer

## Description

*Please add a description here. This will become the commit message of the merge request later.*

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-08-15 11:40 UTC, sbernauer commented on demos/demos-v1.yaml
> +      - plainYaml: demos/kafka-druid-earthquake-data/setup-superset.yaml # TODO
WIP

2022-08-15 11:40 UTC, sbernauer commented on demos/kafka-druid-earthquake-data/setup-superset.yaml
> +          command: ["bash", "-c", "curl -o superset-assets.zip https://raw.githubusercontent.com/stackabletech/stackablectl/demo-kafa-druid-earthquake-data/demos/kafka-druid-earthquake-data/superset-
WIP

2022-08-16 12:42 UTC, maltesander requested changes
Demo worked first try. Very nice, the dashboard looks great.
Please have a look sometimes its Job/job, real-time/realtime/near-realtime. Not sure i covered all of that.
Good job anyhow, im fine with merging after the typos/grammar is fixed!

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +** *Superset*: A modern data exploration and visualization platform. This demo uses it to execute SQL queries on Druid and build dashboards
```suggestion
** *Superset*: A modern data exploration and visualization platform. This demo utilizes Superset to retrieve data from Druid via SQL queries and build dashboards on top of that data
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +** *Kafka*:  A distributed event streaming platform for high-performance data pipelines, streaming analytics and data integration. This demos uses it as a event streaming platform to stream the data
```suggestion
** *Kafka*:  A distributed event streaming platform for high-performance data pipelines, streaming analytics and data integration. This demos uses it as a event streaming platform to stream the data in near real-time
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +** *Druid*: A real-time database to power modern analytics applications. This demo uses it to ingest the near-realtime data from Kafka, store it and enable SQL access to it
```suggestion
** *Druid*: A real-time database to power modern analytics applications. This demo uses it to ingest the near real-time data from Kafka, store it and enable to access the data via SQL
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +Starting all of the product instances might take an considerable amount of time depending on your internet connectivity.
```suggestion
Starting all of the product instances might take a considerable amount of time depending on your internet connectivity.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +Kafka is used as an event streaming platform to stream the data in near-realtime.
```suggestion
Kafka is used as an event streaming platform to stream the data in near real-time.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +The testdata will be put in a topic called `earthquakes`.
```suggestion
The test data will be put in a topic called `earthquakes`.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +The records get produced (put in) by the testdata-generator and are consumed (read) by Druid afterwards in the same order they where produced.
```suggestion
The records get produced (put in) by the test data generator and are consumed (read) by Druid afterwards in the same order they where produced.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +To endpoint where Kafka is reachable is given in the `kafka` endpoint from the `kafka` service in your `stackablectl services list` command output (`172.18.0.4:30968` in this case).
```suggestion
In order to connect to Kafka, use the `kafka` endpoint from the `kafka` service in your `stackablectl services list` command output (`172.18.0.4:30968` in this case).
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +You can see the Kafka consists of one broker and the topic `earthquakes` has been created.
```suggestion
You can see that Kafka consists of one broker and the topic `earthquakes` has been created.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +Druid is used to ingest the near-realtime data from Kafka, store it and enable SQL access to it.
```suggestion
Druid is used to ingest the near real-time data from Kafka, store it and enable SQL access to it.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +The demo has started a ingestion job reading earthquake records from the Kafka topic `earthquakes` and saving it into Druids storage.
```suggestion
The demo has started an ingestion job reading earthquake records from the Kafka topic `earthquakes` and saving it into Druids deep storage.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +To achieve this you first have to on `Query` at the top.
```suggestion
To achieve this you first have to click on `Query` at the top.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +Superset gives the ability to execute SQL queries and build dashboards.
```suggestion
Superset provides the ability to execute SQL queries and build dashboards.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +On the left side you can modify the chart and click on `Run` to see the effect.
The typo being capitalization or what?

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +To look at geographical distribution of the earthquakes you have to click on the tab `Charts` at the top again.
```suggestion
To look at the geographical distribution of the earthquakes you have to click on the tab `Charts` at the top again.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +If you do not want to make on up you can use the following:
```suggestion
If you do not want to make one up, you can use the following:
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +On prefix corresponds to on segment which in turn contains all the data of a year.
```suggestion
One prefix corresponds to on segment which in turn contains all the data of a year.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +If you don't see any years or for files the reason is, that Druid has not saved it's data from memory to the deep storage (in this case S3).
```suggestion
If you don't see any years or files, the reason is that Druid has not saved it's data from memory to the deep storage (in this case S3).
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +Druid ingested the data near-realtime into its datasource and enabled SQL access to it.
```suggestion
Druid ingested the data near real-time into its data source and enabled SQL access to it.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +Within Superset (or the Druid webinterface) you can execute arbitrary SQL statements to explore the taxi data.
```suggestion
Within Superset (or the Druid webinterface) you can execute arbitrary SQL statements to explore the earthquake data.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +You can use a kafka client like https://docs.confluent.io/platform/current/app-development/kafkacat-usage.html[kafkacat] to create new topics and  ingest data.
```suggestion
You can use a kafka client like https://docs.confluent.io/platform/current/app-development/kafkacat-usage.html[kafkacat] to create new topics and ingest data.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +Using the Druid webinterface you can start a ingestion job that consumes the data and stores it in an internal datasource.
```suggestion
Using the Druid web interface, you can start an ingestion job that consumes the data and stores it in an internal data source.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +Afterwards the datasource is available for analysis within Druid and Superset the same way the earthquake data is.
```suggestion
Afterwards the data source is available to be analyzed within Druid and Superset the same way the earthquake data is.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/trino-taxi-data.adoc
> +You can have a look at the testdata within the MinIO Webinterface by opening the given `minio` endpoint `console-http` from your `stackablectl services list` command output.
```suggestion
You can have a look at the testdata within the MinIO web interface by opening the given `minio` endpoint `console-http` from your `stackablectl services list` command output.
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/trino-taxi-data.adoc
> +** *Superset*: A modern data exploration and visualization platform. This demo uses it to execute SQL queries on Trino and build dashboards
```suggestion
** *Superset*: A modern data exploration and visualization platform. This demo utilizes Superset to retrieve data from Trino via SQL queries and build dashboards on top of that data
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/demos/trino-taxi-data.adoc
> +=== View dashboard
```suggestion
=== View the dashboard
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/quickstart.adoc
> +kafka-druid-earthquake-data         kafka-druid-superset-s3   Demo ingestion earthquake data into Kafka, streaming it into Druid and creating a Superset dashboard
```suggestion
kafka-druid-earthquake-data         kafka-druid-superset-s3   Demo to ingest earthquake data into Kafka, streaming it into Druid and creating a Superset dashboard
```

2022-08-16 12:42 UTC, maltesander commented on stacks/stacks-v1.yaml
> +      - plainYaml: stacks/kafka-druid-superset-s3/superset.yaml # TODO
That TODO is for before merging?

2022-08-16 12:42 UTC, maltesander commented on demos/demos-v1.yaml
> +    description:  Demo ingestion earthquake data into Kafka, streaming it into Druid and creating a Superset dashboard
```suggestion
    description:  Demo to ingest earthquake data into Kafka, streaming it into Druid and creating a Superset dashboard
```

2022-08-16 12:42 UTC, maltesander commented on docs/modules/ROOT/pages/commands/demo.adoc
> +kafka-druid-earthquake-data         kafka-druid-superset-s3   Demo ingestion earthquake data into Kafka, streaming it into Druid and creating a Superset dashboard
If you fix this line in demos-v1.yaml do not forget to update here!

2022-08-16 13:19 UTC, sbernauer commented on demos/demos-v1.yaml
> +      - plainYaml: demos/kafka-druid-earthquake-data/setup-superset.yaml # TODO
I have to switch to a URL pointing to the main branch and not to a file on my (our your) disk that only exists within the feature-branch

2022-08-16 13:21 UTC, sbernauer commented on stacks/stacks-v1.yaml
> +      - plainYaml: stacks/kafka-druid-superset-s3/superset.yaml # TODO
exactly

2022-08-16 13:41 UTC, sbernauer commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +On the left side you can modify the chart and click on `Run` to see the effect.
typo in chart name has been fixed

2022-08-16 14:14 UTC, maltesander requested changes
Only minor stuff left over

2022-08-16 14:14 UTC, maltesander commented on demos/kafka-druid-earthquake-data/download_earthquake_data.sh
> +# rm -f 19*.csv 20*.csv earthquakes.csv
leftover?

2022-08-16 14:14 UTC, maltesander commented on docs/modules/ROOT/pages/quickstart.adoc
> +The demos create Kubernetes jobs, that will populate testdata and talk to the installed products to process the data.
```suggestion
The demos create Kubernetes jobs, that will populate test data and talk to the installed products to process the data.
```

2022-08-16 14:14 UTC, maltesander commented on docs/modules/ROOT/pages/quickstart.adoc
> +After the products being ready they should turn green and everything should settle down.
```suggestion
After the products are ready they should turn green and everything should settle down.
```

2022-08-16 14:14 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +You can see the available datasources by clicking on `Datasources` at the top.
Im pretty sure its data source (when mentioning the druid tab `Datasources` its fine). This is used alot, i would go for a refactor.
```suggestion
=== Query the data source
The started ingestion job has automatically created the Druid data source `earthquakes`.
You can see the available data sources by clicking on `Datasources` at the top.
```

2022-08-16 14:14 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-earthquake-data.adoc
> +You can use a kafka client like https://docs.confluent.io/platform/current/app-development/kafkacat-usage.html[kafkacat] to create new topics and ingest data.
```suggestion
You can use a Kafka client like https://docs.confluent.io/platform/current/app-development/kafkacat-usage.html[kafkacat] to create new topics and ingest data.
```

2022-08-16 14:32 UTC, sbernauer commented on demos/kafka-druid-earthquake-data/download_earthquake_data.sh
> +# rm -f 19*.csv 20*.csv earthquakes.csv
Nope, it's documented here for development purposes. But we don't want to execute is automatically

2022-08-16 14:41 UTC, sbernauer commented on demos/kafka-druid-earthquake-data/download_earthquake_data.sh
> +# rm -f 19*.csv 20*.csv earthquakes.csv
Added a comment to clarify

2022-08-16 14:48 UTC, maltesander requested changes
One more :D

2022-08-16 14:48 UTC, maltesander approved these changes
Awesome! LGTM.

2022-08-16 14:49 UTC, sbernauer commented
bors r+

2022-08-16 14:50 UTC, closed without merging