Add demo kafka-druid-water-level-data
stackabletech/stackablectl pull request #76
Opened 2022-08-18 10:19 UTC by sbernauer

## Description

Demo is basically finished, Dashboard could be further improved. Data is from https://www.pegelonline.wsv.de/gast/start.
It will bulk-load the past 31 days from the API and than start scraping the stations approximately every 2 minutes.
Demo is build on top of the existing `kafka-druid-superset-s3` stack. Stacks ftw :rocket: 
Docs will need to follow as I currently have lots of other docs to write.
Run from feature-branch with
`stackablectl --additional-demos-file demos/demos-v1.yaml --additional-stacks-file stacks/stacks-v1.yaml demo install kafka-druid-water-level-data`

Dashboard looks something like
![Screenshot_20220818_120529](https://user-images.githubusercontent.com/29303194/185370281-cee5ab49-e1a5-431e-8be1-450d3984e7a0.png)

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-08-18 10:20 UTC, sbernauer commented on demos/demos-v1.yaml
> +      - plainYaml: demos/kafka-druid-water-level-data/setup-superset.yaml # TODO
Change before merging

2022-08-18 10:20 UTC, sbernauer commented on demos/kafka-druid-water-level-data/setup-superset.yaml
> +          # TODO Change to https://raw.githubusercontent.com/stackabletech/stackablectl/main/demos/kafka-druid-water-level-data/superset-assets.zip
Change before merging

2022-08-18 10:20 UTC, sbernauer commented on stacks/stacks-v1.yaml
> +      - plainYaml: stacks/kafka-druid-superset-s3/druid.yaml
Change before merging

2022-08-19 09:28 UTC, maltesander requested changes
Demo works great. Currently at 10,218,794 measurements. Just some language corrections.

2022-08-19 09:28 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +From the output you can see, that the last measurement record was produced at the timestamp `1660831499070` which translates to `Do 18. Aug 16:04:59 CEST 2022` (using the command `date -d @1660831499
```suggestion
The output shows that the last measurement record was produced at the timestamp `1660831499070` which translates to `Do 18. Aug 16:04:59 CEST 2022` (using the command `date -d @1660831499`).
```

2022-08-19 09:28 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +The `Avg. row size (bytes)` shows, that a typical `measurement` record has is `4` bytes large, while a `station` record has `213` bytes, which is more than 50 times the size.
```suggestion
The `Avg. row size (bytes)` shows, that a typical `measurement` record has `4` bytes, while a `station` record has `213` bytes, which is more than 50 times the size.
```

2022-08-19 09:28 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +So with choosing two dedicated topics over a single topic the demo was able to save 50x of storage and compute costs.
```suggestion
So with choosing two dedicated topics over a single topic, this demo was able to save 50x of storage and computation costs.
```

2022-08-19 09:28 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +In this case the `measurements` datasource is partitioned by the day of the measurement, resulting in 33 segments.
```suggestion
By clicking on the `measurements` data source you can see the segments of which the data source consists of.
In this case the `measurements` data source is partitioned by the day of the measurement, resulting in 33 segments.
```

2022-08-19 09:28 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +Log in with the credentials username `admin`, password `admin`.
```suggestion
Log in with the username `admin` and password `admin`.
```

2022-08-19 09:28 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +=== View station distribution on world map
```suggestion
=== View the station distribution on the world map
```

2022-08-19 09:28 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +The stations are of course placed alongside of open waters.
Open waters refers to oceans or seas.
```suggestion
The stations are of course placed alongside of waters.
```

2022-08-19 09:28 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +They are colored by the water they measure, so all stations of a water have the same color.
```suggestion
They are colored by the waters they measure, so all stations alongside a body of water have the same color.
```

2022-08-19 09:28 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +You can also find out the number of measurements for every water:
```suggestion
You can also find out the number of measurements for every body of water:
```

2022-08-19 09:28 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +What might also be interesting is the average and current measurement of the stations:
```suggestion
What might also be interesting is the average and current amount of measurement of the stations:
```

2022-08-19 09:28 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +Open the `minio` endpoint `console-http` in your browser (http://172.18.0.5:32595 in this case).
Does it make sense to repeat? With all the images and text the last list for the services is far on top.
```suggestion
Open the `minio` endpoint `console-http` retrieved by `stackablectl services list` in your browser (http://172.18.0.5:32595 in this case).
```

2022-08-19 09:28 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +Log in with the credentials username `root`, password `rootroot`.
```suggestion
Log in with the username `root` and password `rootroot`.
```

2022-08-19 09:28 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +You can see the druid has created a folder for both of the two datasources.
```suggestion
You can see the druid has created a folder for both data sources.
```

2022-08-19 09:28 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +One prefix corresponds to on segment which in turn contains all the measurements of a day.
```suggestion
One prefix corresponds to one segment which in turn contains all the measurements of a day.
```

2022-08-19 09:28 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +If you don't see any folders or files, the reason is that Druid has not saved it's data from memory to the deep storage.
```suggestion
If you don't see any folders or files, the reason is that Druid has not saved its data from memory to the deep storage yet.
```

2022-08-19 09:28 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +Druid ingested the data near real-time into its datasource and enabled SQL access to it.
```suggestion
Druid ingested the data near real-time into its data source and enabled SQL access to it.
```

2022-08-19 09:33 UTC, sbernauer commented on demos/kafka-druid-water-level-data/ingest-test-data.yaml
> +    STATIONS_TOPIC = "stations"
As for developing I like having a comment that show on how to develop the stuff. Also i think it's harder to accidentally check in an local IP

2022-08-19 09:33 UTC, sbernauer commented on demos/kafka-druid-water-level-data/setup-superset.yaml
> +    username = "admin"
As for developing I like having a comment that show on how to develop the stuff. Also i think it's harder to accidentally check in an local IP

2022-08-19 09:34 UTC, sbernauer commented on demos/kafka-druid-water-level-data/setup-superset.yaml
> +    #     f.write(result.content)
Definitely keep. When you create dashboards you have to use the Superset API to retrieve the zip file.
(That's also the reason i want to keep the `# base_url = "http://172.18.0.4:31024"` above)

2022-08-19 10:38 UTC, sbernauer commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +This can lead to transmitting and storing the information of e.g. the longitude of a station multiple thousand times.
Changed to `This leads to transmitting and storing duplicated information of e.g. the longitude of a station many times, resulting in increased network traffic and storage usage.`

2022-08-19 10:40 UTC, sbernauer commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +What might also be interesting is the average and current measurement of the stations:
It shows whatever the last measurement was. Like how many meters the water level is. This column does not show the amount/number of measurements

2022-08-19 10:43 UTC, sbernauer commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +If not, that's no big deal as you would see nearly the exact same output.
Changed to `If not, that's no big deal, as you would see nearly the exact same output if you would be able execute the commands.`
Is that more clear?

2022-08-19 10:43 UTC, sbernauer commented
Feedback addressed

2022-08-19 10:53 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +What might also be interesting is the average and current measurement of the stations:
Ok got it wrong then.

2022-08-19 10:53 UTC, maltesander commented on demos/kafka-druid-water-level-data/setup-superset.yaml
> +    username = "admin"
> Also i think it's harder to accidentally check in an local IP
I dont get that?

2022-08-19 11:06 UTC, sbernauer commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +If not, that's no big deal as you would see nearly the exact same output.
Ok maybe we should just remove the sentence.
I want to say "If you don't have kcat install thats fine. There is no additional benefit in running this commands as they would produce the exact same output as the commands in this docs do. You can simply look at the responses here in this document. But trust me, you would get the same results"

2022-08-19 11:09 UTC, sbernauer commented on demos/kafka-druid-water-level-data/setup-superset.yaml
> +    username = "admin"
Please disregard that, i don't want to confuse you ^^
I think it boils down to personal taste and i personally prefer having it a second - commented out - line to make clear that you are supposed to change that line if you want to test/develop this script locally.
If you have a strong opinion to remove it just say so and i will remove it (as I said personal taste)

2022-08-19 11:10 UTC, sbernauer commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +If not, that's no big deal as you would see nearly the exact same output.
Removed the sentence. Is that ok for you?

2022-08-19 12:03 UTC, maltesander commented on docs/modules/ROOT/pages/demos/kafka-druid-water-level-data.adoc
> +If not, that's no big deal as you would see nearly the exact same output.
Yeah i think thats better :)

2022-08-19 12:49 UTC, maltesander commented on demos/kafka-druid-water-level-data/setup-superset.yaml
> +    username = "admin"
Ok but then i would rather just add a comment instead of code (the ip and port wont be reusable anyways). Now it just looks like dead code tbh:
```
# This url must be changed for local testing / developing purposes
base_url = "http://superset-external:8088"
username = "admin"
```

2022-08-19 12:53 UTC, maltesander commented on demos/kafka-druid-water-level-data/ingest-test-data.yaml
> +    STATIONS_TOPIC = "stations"
see below. But i can live with having it like this.

2022-08-19 13:47 UTC, maltesander approved these changes
Awesome! LGTM.

2022-08-19 13:48 UTC, sbernauer commented
Thx!

2022-08-19 13:48 UTC, sbernauer commented
bors r+

2022-08-19 13:49 UTC, closed without merging